[2023-05-01T02:30:29.018+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T01:30:00+00:00 [queued]>
[2023-05-01T02:30:29.032+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T01:30:00+00:00 [queued]>
[2023-05-01T02:30:29.033+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T02:30:29.034+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T02:30:29.036+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T02:30:29.055+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-01 01:30:00+00:00
[2023-05-01T02:30:29.062+0000] {standard_task_runner.py:55} INFO - Started process 974 to run task
[2023-05-01T02:30:29.074+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-01T01:30:00+00:00', '--job-id', '1986', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp8nm6p8od']
[2023-05-01T02:30:29.077+0000] {standard_task_runner.py:83} INFO - Job 1986: Subtask scrape_teams_9-16
[2023-05-01T02:30:29.186+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T01:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T02:30:29.256+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T01:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T01:30:00+00:00
[2023-05-01T02:30:29.267+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003c810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:29.268+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003c810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:29.269+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:30:30.278+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:30.280+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:30.281+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:30:31.294+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00491d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:31.302+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00491d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:31.304+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:30:32.314+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:32.315+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:32.316+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:30:33.330+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:33.331+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:33.334+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:30:34.346+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:34.347+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:34.349+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:30:35.365+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:35.367+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:35.371+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:30:36.387+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:36.389+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:36.391+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:30:37.405+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:37.407+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:37.409+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:30:38.418+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:38.421+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:38.422+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:30:39.437+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:39.446+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:39.448+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:30:40.475+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:40.479+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:40.482+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:30:41.510+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00491d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:41.514+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00491d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:41.519+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:30:42.537+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:42.540+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:42.542+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:30:43.563+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:43.568+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:43.571+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:30:44.586+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00493d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:44.590+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00493d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:44.594+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:30:45.626+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:45.630+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:45.634+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:30:46.676+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:46.680+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:46.683+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:30:47.694+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:47.696+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:47.700+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:30:48.742+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:48.746+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:48.749+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:30:49.774+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:49.778+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:49.780+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:30:50.792+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:50.796+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:50.798+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:30:51.811+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00491d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:51.813+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00491d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:51.814+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:30:52.824+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:52.828+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:52.829+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:30:53.854+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:53.860+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:53.864+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:30:54.884+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:54.887+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:54.888+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:30:55.917+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:55.921+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:55.922+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:30:56.951+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:56.954+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:56.960+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:30:57.967+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:57.970+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:57.971+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:30:58.990+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00493d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:58.993+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00493d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:58.995+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:00.014+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:00.029+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:00.061+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:01.106+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:01.108+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:01.109+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:02.122+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:02.125+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:02.126+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:03.136+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:03.137+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:03.138+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:04.147+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:04.154+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:04.156+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:05.164+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:05.167+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:05.169+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:06.177+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:06.178+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:06.179+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:07.188+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:07.190+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:07.191+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:08.199+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:08.200+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:08.202+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:09.212+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:09.214+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:09.215+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:10.224+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:10.225+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:10.226+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:11.239+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:11.242+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:11.244+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:12.256+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:12.258+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:12.260+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:13.271+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:13.274+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:13.275+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:14.282+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:14.283+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:14.284+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:15.291+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:15.293+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:15.294+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:16.307+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:16.309+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:16.310+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:17.339+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:17.341+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:17.344+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:18.356+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:18.358+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:18.361+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:19.373+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:19.377+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:19.378+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:20.391+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00493d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:20.394+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00493d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:20.395+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:21.423+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:21.427+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:21.431+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:22.459+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:22.469+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:22.472+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:23.486+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:23.491+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:23.493+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:24.508+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:24.510+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:24.512+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:25.524+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:25.526+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:25.527+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:26.535+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:26.538+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:26.541+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:27.559+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:27.564+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:27.567+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:28.575+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:28.577+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:28.579+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:29.586+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:29.589+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:29.590+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:30.602+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:30.603+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:30.605+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:31.614+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:31.618+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:31.620+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:32.643+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:32.649+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:32.651+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:33.661+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:33.664+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:33.665+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:34.678+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:34.680+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:34.681+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:35.689+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:35.691+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:35.694+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:36.708+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:36.710+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:36.712+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:37.720+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:37.721+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:37.723+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:38.732+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:38.733+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:38.734+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:39.744+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:39.745+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:39.749+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:40.760+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:40.763+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:40.764+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:41.786+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:41.790+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00495d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:41.793+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:42.815+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:42.821+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00499d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:42.823+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:43.831+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:43.833+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:43.835+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:44.843+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:44.844+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:44.848+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:45.859+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:45.860+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0049210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:45.861+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:46.869+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:46.870+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00492d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:46.872+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:47.883+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8d184d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:47.886+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8d184d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:47.888+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:48.899+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cfcd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:48.902+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cfcd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:48.904+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:49.912+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa6e4f450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:49.916+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa6e4f450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:49.917+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:50.930+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:50.932+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:50.933+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:51.954+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:51.959+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:51.961+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:52.981+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:52.985+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:52.989+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:54.002+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:54.004+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:54.005+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:55.019+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:55.022+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:55.023+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:56.033+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:56.036+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:56.038+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:57.045+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002fc90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:57.046+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002fc90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:57.047+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:58.057+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:58.061+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa002f250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:58.062+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:59.075+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_9-16.csv
[2023-05-01T02:31:59.078+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T02:31:59.098+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_9-16, execution_date=20230501T013000, start_date=20230501T023029, end_date=20230501T023159
[2023-05-01T02:31:59.167+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T02:31:59.195+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
