[2023-05-01T10:48:55.653+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T09:30:00+00:00 [queued]>
[2023-05-01T10:48:55.679+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T09:30:00+00:00 [queued]>
[2023-05-01T10:48:55.682+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T10:48:55.683+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T10:48:55.684+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T10:48:55.707+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-01 09:30:00+00:00
[2023-05-01T10:48:55.725+0000] {standard_task_runner.py:55} INFO - Started process 5754 to run task
[2023-05-01T10:48:55.740+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-01T09:30:00+00:00', '--job-id', '2036', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmparf82jyf']
[2023-05-01T10:48:55.747+0000] {standard_task_runner.py:83} INFO - Job 2036: Subtask scrape_teams_9-16
[2023-05-01T10:48:55.985+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T09:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T10:48:56.159+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T09:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T09:30:00+00:00
[2023-05-01T10:48:56.172+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:56.174+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:56.182+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T10:48:57.193+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:57.195+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:57.197+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T10:48:58.209+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:58.214+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:58.215+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T10:48:59.224+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:59.226+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:59.227+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T10:49:00.240+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:00.242+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:00.244+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T10:49:01.276+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:01.290+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:01.296+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T10:49:02.308+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:02.312+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:02.316+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T10:49:03.332+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:03.335+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:03.338+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T10:49:04.352+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:04.354+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:04.355+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T10:49:05.369+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:05.371+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:05.373+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T10:49:06.398+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:06.402+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:06.410+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T10:49:07.433+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:07.441+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:07.442+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T10:49:08.469+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:08.471+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:08.472+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T10:49:09.484+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:09.485+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:09.486+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T10:49:10.497+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:10.498+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:10.499+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T10:49:11.507+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:11.509+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:11.511+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T10:49:12.534+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:12.538+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:12.541+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T10:49:13.560+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:13.563+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:13.564+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T10:49:14.576+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:14.577+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:14.579+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T10:49:15.620+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:15.658+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:15.662+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T10:49:16.683+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:16.688+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:16.691+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T10:49:17.723+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:17.726+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:17.729+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T10:49:18.753+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:18.756+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:18.761+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T10:49:19.774+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:19.776+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:19.778+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T10:49:20.790+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:20.791+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:20.792+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T10:49:21.812+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:21.819+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:21.823+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T10:49:22.834+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:22.836+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:22.837+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T12:11:35.310+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:35.313+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:35.318+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T12:11:36.344+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:36.346+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:36.348+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T12:11:37.354+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:37.356+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:37.357+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T12:11:38.367+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:38.369+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:38.371+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T12:11:39.387+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:39.390+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003eb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:39.391+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T12:11:40.398+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:40.400+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:40.401+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T12:11:41.408+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:41.409+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ee90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:41.410+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T12:11:42.422+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:42.430+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:42.431+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T12:11:43.439+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:43.441+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:43.442+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T12:11:44.450+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:44.451+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:44.454+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T12:11:45.470+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004bcd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:45.473+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004bcd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:45.474+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T12:11:46.483+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004bc90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:46.486+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004bc90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:46.489+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T12:11:47.496+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:47.498+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:47.499+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T12:11:48.513+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:48.516+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:48.517+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T12:11:49.529+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:49.531+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:49.532+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T12:11:50.611+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:50.614+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:50.617+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T12:11:51.624+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:51.627+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004b9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T12:11:51.628+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T12:11:52.629+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-01T12:11:52.639+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5754. PIDs of all processes in the group: [5754]
[2023-05-01T12:11:52.640+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5754
[2023-05-01T12:11:52.680+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-01T12:11:52.683+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-01T12:11:52.685+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-01T12:11:52.686+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T13:18:52.780+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=5754, name='airflow task ru', status='sleeping', started='10:48:55') did not respond to SIGTERM. Trying SIGKILL
[2023-05-01T13:18:52.793+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 5754
[2023-05-01T13:18:52.849+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5754, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='10:48:55') (5754) terminated with exit code Negsignal.SIGKILL
[2023-05-01T13:18:52.851+0000] {standard_task_runner.py:170} ERROR - Job 2036 was killed before it finished (likely due to running out of memory)
