[2023-05-02T16:40:25.135+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-02T15:30:00+00:00 [queued]>
[2023-05-02T16:40:25.151+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-02T15:30:00+00:00 [queued]>
[2023-05-02T16:40:25.159+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T16:40:25.160+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T16:40:25.163+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T16:40:25.179+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_17-24> on 2023-05-02 15:30:00+00:00
[2023-05-02T16:40:25.188+0000] {standard_task_runner.py:55} INFO - Started process 22693 to run task
[2023-05-02T16:40:25.199+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_17-24', 'scheduled__2023-05-02T15:30:00+00:00', '--job-id', '2235', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp13s2voux']
[2023-05-02T16:40:25.205+0000] {standard_task_runner.py:83} INFO - Job 2235: Subtask scrape_teams_17-24
[2023-05-02T16:40:25.320+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-02T15:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-02T16:40:25.389+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_17-24
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T15:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T15:30:00+00:00
[2023-05-02T16:40:25.401+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:25.416+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:25.417+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T16:40:26.429+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:26.432+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:26.434+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T16:40:27.441+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:27.443+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:27.444+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T16:40:28.470+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:28.472+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:28.474+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T16:40:29.489+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ac50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:29.491+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ac50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:29.505+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T16:40:30.516+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:30.519+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:30.521+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T16:40:31.529+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:31.535+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:31.537+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T16:40:32.556+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:32.559+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:32.563+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T16:40:33.577+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ac50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:33.579+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ac50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:33.580+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T16:40:34.588+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:34.589+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:34.590+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T16:40:35.597+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:35.598+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:35.599+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T16:40:36.608+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:36.611+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:36.612+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T16:40:37.638+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:37.640+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:37.641+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T16:40:38.650+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:38.652+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:38.653+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T16:40:39.663+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:39.665+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:39.666+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T16:40:40.674+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:40.676+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:40.677+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T16:40:41.688+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:41.690+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:41.691+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T16:40:42.699+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:42.701+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:42.702+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T16:40:43.712+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:43.724+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:43.727+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T16:40:44.752+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:44.761+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:44.772+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T16:40:45.782+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:45.786+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:45.787+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T16:40:46.799+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:46.804+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:46.805+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T16:40:47.819+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:47.823+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:47.843+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T16:40:48.882+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:48.888+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:48.891+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T16:40:49.921+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:49.930+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:49.935+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T16:40:50.955+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:50.959+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:50.961+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T16:40:51.998+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:52.012+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T16:40:52.015+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T17:12:32.938+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:32.945+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:32.948+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T17:12:34.010+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:34.014+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:34.018+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T17:12:35.074+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:35.082+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:35.085+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T17:12:36.104+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:36.109+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:36.113+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T17:12:37.127+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:37.128+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:37.130+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T17:12:38.150+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:38.155+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:38.161+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T17:12:39.196+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:39.202+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:39.205+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T17:12:40.239+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:40.241+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:40.243+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T17:12:41.271+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:41.288+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:41.291+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T17:12:42.302+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:42.304+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:42.306+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T17:12:43.319+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:43.321+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:43.323+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T17:12:44.357+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:44.362+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:44.370+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T17:12:45.387+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:45.392+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0054590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T17:12:45.394+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T17:12:45.508+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T17:12:45.524+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 22693. PIDs of all processes in the group: [22693]
[2023-05-02T17:12:45.525+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 22693
[2023-05-02T17:12:45.527+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T17:12:45.553+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=22693, status='terminated', exitcode=0, started='16:40:24') (22693) terminated with exit code 0
