[2023-04-30T19:16:50.204+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-04-30T17:30:00+00:00 [queued]>
[2023-04-30T19:16:50.217+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-04-30T17:30:00+00:00 [queued]>
[2023-04-30T19:16:50.218+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T19:16:50.219+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-30T19:16:50.220+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T19:16:50.235+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_17-24> on 2023-04-30 17:30:00+00:00
[2023-04-30T19:16:50.242+0000] {standard_task_runner.py:55} INFO - Started process 355 to run task
[2023-04-30T19:16:50.254+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_17-24', 'scheduled__2023-04-30T17:30:00+00:00', '--job-id', '1938', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp4yjgipdl']
[2023-04-30T19:16:50.257+0000] {standard_task_runner.py:83} INFO - Job 1938: Subtask scrape_teams_17-24
[2023-04-30T19:16:50.368+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-04-30T17:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-04-30T19:16:50.495+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_17-24
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T17:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T17:30:00+00:00
[2023-04-30T19:16:50.508+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:50.509+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:50.510+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T19:16:51.524+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0038d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:51.525+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0038d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:51.526+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T19:16:52.535+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:52.537+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:52.538+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T19:16:53.549+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00449d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:53.551+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00449d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:53.554+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T19:16:54.571+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:54.574+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:54.577+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T19:16:55.586+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:55.587+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:55.588+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T19:16:56.598+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:56.601+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:56.603+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T19:16:57.614+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00447d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:57.617+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00447d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:57.618+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T19:16:58.626+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:58.629+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:58.630+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T19:16:59.650+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:59.657+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:16:59.659+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T19:17:00.668+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:00.671+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:00.672+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T19:17:01.684+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:01.689+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:01.693+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T19:17:02.707+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:02.709+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:02.711+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T19:17:03.729+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:03.732+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:03.734+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T19:17:04.742+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:04.743+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:04.744+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T19:17:05.753+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:05.754+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:05.756+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T19:17:06.771+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:06.774+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:06.775+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T19:17:07.793+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00449d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:07.797+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00449d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:07.801+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T19:17:08.816+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:08.819+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:08.820+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T19:17:09.841+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:09.847+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:09.849+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T19:17:10.872+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:10.877+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:10.882+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T19:17:11.894+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:11.896+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:11.897+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T19:17:12.911+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:12.913+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:12.914+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T19:17:13.925+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00447d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:13.928+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00447d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:13.931+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T19:17:14.944+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:14.947+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:14.949+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T19:17:15.960+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:15.962+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:15.963+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T19:17:16.977+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:16.979+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:16.981+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T19:17:17.994+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:17.997+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T19:17:18.000+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:03:45.909+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:45.910+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:45.911+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:03:46.928+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:46.935+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:46.938+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:03:47.948+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:47.951+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:47.952+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:03:48.962+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:48.963+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:48.964+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:03:49.975+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:49.980+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:49.982+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:03:51.001+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:51.006+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:51.010+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:03:52.020+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:52.022+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:52.023+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:03:53.031+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:53.033+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:53.037+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:03:54.046+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:54.048+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:54.049+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:03:55.067+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00447d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:55.068+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00447d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:55.070+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:03:56.080+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:56.081+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:56.083+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:03:57.094+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:57.096+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:57.097+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:03:58.115+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:58.119+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:58.123+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:03:59.155+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:59.158+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:59.161+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:04:00.174+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:00.178+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:00.179+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:04:01.192+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:01.198+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:01.201+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:04:02.213+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:02.216+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:02.219+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:04:03.236+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:03.239+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:03.242+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:04:04.259+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:04.261+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:04.263+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:04:05.274+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:05.276+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:05.280+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:04:06.290+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:06.291+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:06.293+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:04:07.306+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:07.307+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:07.309+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:04:08.343+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:08.349+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:08.352+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:04:09.376+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:09.380+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:09.384+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:04:10.411+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:10.417+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:10.420+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:04:11.437+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:11.444+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:11.446+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:04:12.456+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:12.457+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:12.458+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:04:13.472+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:13.475+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:13.478+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:04:14.489+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:14.492+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:14.497+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:38:49.534+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:49.537+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:49.540+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:38:50.557+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:50.558+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:50.559+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:38:51.692+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:51.694+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:51.697+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:38:52.714+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:52.716+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:52.717+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:38:53.727+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:53.730+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:53.731+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:38:54.753+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:54.756+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:54.757+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:38:55.776+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:55.780+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:55.784+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:38:56.795+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:56.796+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:56.797+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:38:57.805+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:57.809+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:57.813+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:38:58.832+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:58.833+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:58.835+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:38:59.847+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:59.849+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:59.851+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:39:00.864+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:00.865+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:00.866+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:39:01.875+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:01.877+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:01.878+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:39:02.905+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:02.907+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:02.908+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:39:03.918+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:03.919+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:03.921+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:39:04.929+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:04.930+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:04.933+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:39:05.942+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:05.944+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:05.946+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:39:06.957+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:06.959+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:06.965+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:39:07.974+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:07.977+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:07.978+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:39:08.994+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:08.995+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:08.997+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:39:10.017+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8d078d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:10.020+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8d078d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:10.022+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:39:11.043+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:11.046+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:11.048+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:39:12.061+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:12.065+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:12.066+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:39:13.083+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:13.090+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:13.093+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:39:14.105+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:14.106+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:14.108+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:39:15.116+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:15.118+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:15.119+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:39:16.126+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:16.127+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:16.128+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:39:17.139+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:17.142+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:17.144+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:39:18.174+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:18.186+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:18.191+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:39:19.221+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:19.223+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:19.227+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T21:23:09.030+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:09.031+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:09.033+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T21:23:10.081+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_17-24.csv
[2023-04-30T21:23:10.087+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-30T21:23:10.137+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_17-24, execution_date=20230430T173000, start_date=20230430T191650, end_date=20230430T212310
[2023-04-30T21:23:10.235+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-30T21:23:10.290+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
