[2023-05-01T13:00:55.022+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-01T11:30:00+00:00 [queued]>
[2023-05-01T13:00:55.031+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-01T11:30:00+00:00 [queued]>
[2023-05-01T13:00:55.033+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T13:00:55.036+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T13:00:55.042+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T13:00:55.059+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_17-24> on 2023-05-01 11:30:00+00:00
[2023-05-01T13:00:55.066+0000] {standard_task_runner.py:55} INFO - Started process 5806 to run task
[2023-05-01T13:00:55.083+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_17-24', 'scheduled__2023-05-01T11:30:00+00:00', '--job-id', '2044', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpxk8pg_ko']
[2023-05-01T13:00:55.091+0000] {standard_task_runner.py:83} INFO - Job 2044: Subtask scrape_teams_17-24
[2023-05-01T13:00:55.215+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-01T11:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T13:00:55.651+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_17-24
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T11:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T11:30:00+00:00
[2023-05-01T13:00:55.689+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003b510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:55.690+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003b510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:55.691+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T13:00:56.703+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:56.704+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:56.706+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T13:00:57.721+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:57.725+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:57.726+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T13:00:58.749+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:58.754+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:58.756+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T13:00:59.784+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:59.793+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:00:59.796+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T13:01:00.806+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:01:00.808+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:01:00.809+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T13:01:01.817+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:01:01.819+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:01:01.825+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T13:01:06.344+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T13:01:06.762+0000] {helpers.py:80} INFO - Milwaukee Bucks: Successfully scraped!
[2023-05-01T13:01:10.600+0000] {helpers.py:80} INFO - Minnesota Timberwolves: Successfully scraped!
[2023-05-01T13:01:16.118+0000] {helpers.py:80} INFO - New Orleans Pelicans: Successfully scraped!
[2023-05-01T13:01:19.467+0000] {helpers.py:80} INFO - New York Knicks: Successfully scraped!
[2023-05-01T13:18:36.580+0000] {helpers.py:80} INFO - Oklahoma City Thunder: Successfully scraped!
[2023-05-01T13:18:53.437+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-01T13:18:53.453+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5806. PIDs of all processes in the group: [5806]
[2023-05-01T13:18:53.454+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5806
[2023-05-01T13:18:53.459+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-01T13:18:53.490+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-01T13:18:53.491+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-01T13:18:53.492+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T13:18:54.511+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:54.515+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:54.518+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T13:18:55.525+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:55.527+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:55.527+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T13:18:56.550+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:56.554+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:56.559+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T13:18:57.567+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:57.569+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:57.570+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T13:18:58.663+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:58.665+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:58.666+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T13:18:59.675+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:59.677+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:18:59.678+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T13:19:00.693+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfd10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:00.698+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfd10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:00.701+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T13:19:01.733+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:01.753+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:01.755+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T13:19:02.770+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:02.771+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:02.772+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T13:19:03.892+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfe10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:03.955+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfe10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T13:19:03.960+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T14:41:20.021+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf4d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:20.024+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf4d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:20.027+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T14:41:21.050+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:21.051+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:21.055+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T14:41:22.071+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:22.076+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:22.081+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T14:41:23.090+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:23.092+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:23.094+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T14:41:24.101+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:24.104+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:24.105+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T14:41:25.117+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:25.119+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:25.120+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T14:41:26.151+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:26.154+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:26.156+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T14:41:27.166+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:27.168+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:27.171+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T14:41:28.178+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:28.181+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:28.182+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T14:41:29.193+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:29.194+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:29.195+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T14:41:30.202+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfe10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:30.204+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfe10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:30.208+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T14:41:31.215+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:31.216+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:31.217+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T14:41:32.224+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:32.226+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:32.227+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T14:41:33.233+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:33.234+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:33.236+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T14:41:34.242+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfe90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:34.244+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfe90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:34.244+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T14:41:35.252+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:35.255+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bf0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:35.255+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T14:41:36.262+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:36.264+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bff50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:36.265+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T14:41:37.273+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:37.274+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9b3bfa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:37.275+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T14:41:42.982+0000] {helpers.py:80} INFO - Phoenix Suns: Successfully scraped!
[2023-05-01T14:41:43.146+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_17-24.csv
[2023-05-01T14:41:43.213+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T14:41:43.377+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_17-24, execution_date=20230501T113000, start_date=20230501T130055, end_date=20230501T144143
[2023-05-01T14:41:43.748+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5806, status='terminated', exitcode=0, started='13:00:54') (5806) terminated with exit code 0
