[2023-05-01T02:30:29.028+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-01T01:30:00+00:00 [queued]>
[2023-05-01T02:30:29.047+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-01T01:30:00+00:00 [queued]>
[2023-05-01T02:30:29.048+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T02:30:29.050+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T02:30:29.053+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T02:30:29.069+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_17-24> on 2023-05-01 01:30:00+00:00
[2023-05-01T02:30:29.078+0000] {standard_task_runner.py:55} INFO - Started process 975 to run task
[2023-05-01T02:30:29.086+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_17-24', 'scheduled__2023-05-01T01:30:00+00:00', '--job-id', '1987', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp_2o5gkdh']
[2023-05-01T02:30:29.094+0000] {standard_task_runner.py:83} INFO - Job 1987: Subtask scrape_teams_17-24
[2023-05-01T02:30:29.204+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 scheduled__2023-05-01T01:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T02:30:29.275+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_17-24
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T01:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T01:30:00+00:00
[2023-05-01T02:30:29.284+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:29.286+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:29.288+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:30:30.294+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:30.297+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:30.298+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:30:31.309+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:31.313+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:31.316+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:30:32.325+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:32.326+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:32.328+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:30:33.337+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:33.340+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:33.341+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:30:34.349+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:34.351+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:34.352+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:30:35.364+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:35.367+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:35.375+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:30:36.386+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:36.388+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:36.390+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:30:37.405+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:37.407+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:37.409+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:30:38.419+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:38.421+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:38.423+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:30:39.435+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:39.437+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=MkeBucks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:39.441+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:30:40.476+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:40.479+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:40.482+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:30:41.504+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:41.509+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:41.516+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:30:42.536+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:42.540+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:42.543+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:30:43.570+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:43.572+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:43.575+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:30:44.595+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:44.597+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:44.601+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:30:45.632+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:45.635+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:45.638+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:30:46.675+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:46.681+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:46.683+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:30:47.692+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:47.694+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:47.697+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:30:48.732+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:48.738+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:48.741+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:30:49.771+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:49.776+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:49.778+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:30:50.794+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:50.796+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=timberwolves&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:50.799+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:30:51.810+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:51.811+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:51.813+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:30:52.823+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:52.827+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:52.829+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:30:53.861+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:53.868+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:53.872+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:30:54.884+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:54.887+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:54.888+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:30:55.916+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:55.919+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:55.921+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:30:56.944+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:56.949+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:56.952+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:30:57.958+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:57.960+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:57.960+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:30:58.967+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:58.970+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:58.972+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:30:59.979+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:59.980+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:30:59.982+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:00.994+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:00.997+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:01.000+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:02.012+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:02.016+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NOLAPelicans&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:02.018+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:03.026+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:03.027+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:03.028+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:04.036+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:04.038+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:04.039+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:05.061+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:05.064+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:05.067+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:06.086+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:06.089+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:06.093+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:07.103+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:07.104+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:07.106+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:08.114+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:08.115+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:08.116+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:09.126+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:09.128+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:09.131+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:10.156+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:10.162+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:10.165+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:11.196+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:11.200+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:11.204+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:12.231+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:12.233+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:12.236+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:13.248+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:13.252+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=nyknicks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:13.253+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:14.264+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:14.265+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:14.266+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:15.274+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:15.277+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:15.278+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:16.293+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:16.296+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:16.300+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:17.336+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:17.341+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:17.346+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:18.357+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:18.361+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:18.363+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:19.373+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:19.377+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:19.379+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:20.390+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:20.393+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:20.395+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:21.427+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:21.431+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:21.433+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:22.462+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:22.468+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:22.470+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:23.487+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:23.492+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:23.497+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:24.509+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:24.510+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Thunder&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:24.512+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:25.524+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:25.526+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:25.528+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:26.536+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:26.538+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:26.541+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:27.553+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:27.565+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:27.568+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:28.581+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:28.583+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:28.584+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:29.595+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:29.596+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:29.598+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:30.607+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:30.609+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:30.611+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:31.619+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:31.621+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:31.623+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:32.635+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:32.641+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:32.645+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:33.659+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:33.662+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:33.663+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:34.673+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:34.679+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:34.684+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:35.693+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:35.695+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=OrlandoMagic&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:35.700+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:36.710+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:36.712+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:36.713+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:37.720+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:37.721+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:37.723+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:38.731+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:38.732+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:38.734+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:39.743+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:39.745+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:39.748+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:40.760+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:40.763+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:40.764+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:41.786+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:41.791+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:41.794+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:42.812+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:42.815+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:42.820+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:43.831+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:43.833+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:43.834+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:44.841+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:44.843+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:44.847+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:45.856+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:45.858+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:45.860+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:46.868+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:46.871+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=sixers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:46.872+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:47.883+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffb8fa8d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:47.886+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffb8fa8d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:47.887+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:31:48.899+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:48.901+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:48.904+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:31:49.913+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:49.917+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:49.918+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:31:50.930+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:50.932+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:50.933+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:31:51.953+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:51.956+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:51.959+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:31:52.980+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:52.987+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:52.991+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:31:54.002+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:54.004+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:54.007+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:31:55.018+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:55.022+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:55.023+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:31:56.033+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:56.037+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:56.040+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:31:57.046+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:57.047+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:57.048+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:31:58.057+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:58.061+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=suns&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:31:58.062+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:31:59.075+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_17-24.csv
[2023-05-01T02:31:59.078+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T02:31:59.097+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_17-24, execution_date=20230501T013000, start_date=20230501T023029, end_date=20230501T023159
[2023-05-01T02:31:59.168+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T02:31:59.218+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
