[2023-04-28T21:40:33.636+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.join_csv manual__2023-04-28T21:38:35.111987+00:00 [queued]>
[2023-04-28T21:40:33.644+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.join_csv manual__2023-04-28T21:38:35.111987+00:00 [queued]>
[2023-04-28T21:40:33.646+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T21:40:33.647+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T21:40:33.648+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T21:40:33.658+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): join_csv> on 2023-04-28 21:38:35.111987+00:00
[2023-04-28T21:40:33.664+0000] {standard_task_runner.py:55} INFO - Started process 272 to run task
[2023-04-28T21:40:33.668+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'join_csv', 'manual__2023-04-28T21:38:35.111987+00:00', '--job-id', '1688', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp95fbwjh1']
[2023-04-28T21:40:33.672+0000] {standard_task_runner.py:83} INFO - Job 1688: Subtask join_csv
[2023-04-28T21:40:33.732+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.join_csv manual__2023-04-28T21:38:35.111987+00:00 [running]> on host def38439e216
[2023-04-28T21:40:33.783+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=join_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T21:38:35.111987+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T21:38:35.111987+00:00
[2023-04-28T21:40:33.786+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/helpers.py", line 58, in join
    pd.read_csv(f"{AIRFLOW_HOME}/output_teams_1-8.csv"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_teams_1-8.csv'
[2023-04-28T21:40:33.797+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=scrape_and_save_to_csv, task_id=join_csv, execution_date=20230428T213835, start_date=20230428T214033, end_date=20230428T214033
[2023-04-28T21:40:33.806+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1688 for task join_csv ([Errno 2] No such file or directory: '/opt/airflow/output_teams_1-8.csv'; 272)
[2023-04-28T21:40:33.839+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T21:40:33.864+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
