[2023-05-02T13:41:22.807+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-02T12:30:00+00:00 [queued]>
[2023-05-02T13:41:22.829+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-02T12:30:00+00:00 [queued]>
[2023-05-02T13:41:22.831+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T13:41:22.832+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T13:41:22.833+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T13:41:22.851+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_25-30> on 2023-05-02 12:30:00+00:00
[2023-05-02T13:41:22.867+0000] {standard_task_runner.py:55} INFO - Started process 22589 to run task
[2023-05-02T13:41:22.874+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_25-30', 'scheduled__2023-05-02T12:30:00+00:00', '--job-id', '2220', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpqct20z31']
[2023-05-02T13:41:22.882+0000] {standard_task_runner.py:83} INFO - Job 2220: Subtask scrape_teams_25-30
[2023-05-02T13:41:22.982+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-02T12:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-02T13:41:23.066+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_25-30
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T12:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T12:30:00+00:00
[2023-05-02T13:41:23.094+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003c7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:23.095+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003c7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:23.095+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T13:41:24.102+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:24.103+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:24.105+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T13:41:25.123+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:25.154+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:25.156+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T13:41:26.195+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:26.199+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:26.202+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T13:41:27.240+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:27.245+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:27.249+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T13:41:28.270+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:28.275+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:28.284+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T13:41:29.308+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:29.313+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:29.321+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T13:41:30.330+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:30.337+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:30.338+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T13:41:31.357+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:31.363+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:31.368+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T13:41:32.403+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:32.408+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:32.418+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T13:41:33.428+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:33.430+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:33.431+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T13:41:34.447+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:34.468+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:34.470+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T13:41:35.502+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:35.511+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:35.513+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T13:41:36.543+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:36.546+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:36.551+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T13:41:37.591+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:37.593+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:37.595+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T13:41:38.609+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:38.615+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:38.616+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T13:41:39.635+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:39.639+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:39.645+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T13:41:40.654+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:40.656+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:40.657+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T13:41:41.667+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:41.670+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:41.673+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T13:41:42.684+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:42.689+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:42.690+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T13:41:43.707+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:43.711+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:43.718+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T13:41:44.728+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:44.730+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:44.732+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T13:41:45.758+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:45.760+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:45.761+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T13:41:46.774+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:46.778+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:46.781+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T13:41:47.798+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:47.802+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:47.806+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T13:41:48.826+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:48.862+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:48.864+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T13:41:49.877+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:49.886+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:41:49.889+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T13:58:02.927+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:02.930+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:02.932+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T13:58:03.949+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:03.952+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:03.954+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T13:58:04.962+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:04.964+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:04.967+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T13:58:05.987+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:05.990+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:06.004+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T13:58:07.031+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:07.034+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:07.037+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T13:58:08.054+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:08.057+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:08.062+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T13:58:09.080+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:09.085+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:09.088+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T13:58:10.100+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:10.110+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:10.111+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T13:58:11.122+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:11.124+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:11.125+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T13:58:12.151+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:12.154+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:12.156+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T13:58:13.168+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:13.174+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:13.176+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T13:58:14.187+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:14.189+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:14.192+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T13:58:15.205+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:15.209+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T13:58:15.212+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T13:58:15.362+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T13:58:15.367+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 22589. PIDs of all processes in the group: [22589]
[2023-05-02T13:58:15.384+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 22589
[2023-05-02T13:58:15.387+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T13:58:15.447+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=22589, status='terminated', exitcode=0, started='13:41:22') (22589) terminated with exit code 0
