[2023-05-01T14:41:22.636+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T12:30:00+00:00 [queued]>
[2023-05-01T14:41:22.660+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T12:30:00+00:00 [queued]>
[2023-05-01T14:41:22.661+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T14:41:22.662+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T14:41:22.663+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T14:41:22.689+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-01 12:30:00+00:00
[2023-05-01T14:41:22.704+0000] {standard_task_runner.py:55} INFO - Started process 5853 to run task
[2023-05-01T14:41:22.734+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-01T12:30:00+00:00', '--job-id', '2051', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpxpymafoz']
[2023-05-01T14:41:22.737+0000] {standard_task_runner.py:83} INFO - Job 2051: Subtask scrape_teams_1-8
[2023-05-01T14:41:22.883+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T12:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T14:41:23.029+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T12:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T12:30:00+00:00
[2023-05-01T14:41:23.043+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004c750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:23.045+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004c750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:23.049+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T14:41:24.060+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:24.061+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:24.062+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T14:41:25.070+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:25.072+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:25.073+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T14:41:26.088+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:26.091+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:26.092+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T14:41:27.105+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:27.106+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:27.107+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T14:41:28.118+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:28.119+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:28.120+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T14:41:29.129+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:29.130+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:29.132+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T14:41:30.152+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:30.155+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:30.158+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T14:41:31.177+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:31.179+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:31.180+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T14:41:32.186+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:32.188+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:32.189+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T14:41:33.195+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:33.196+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:33.197+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T14:41:34.203+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:34.207+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:34.208+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T14:41:35.216+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:35.218+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:35.218+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T14:41:36.225+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:36.226+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:36.227+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T14:41:37.248+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:37.254+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T14:41:37.256+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T14:41:42.442+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T14:41:44.369+0000] {helpers.py:80} INFO - Boston Celtics: Successfully scraped!
[2023-05-01T15:10:25.181+0000] {helpers.py:80} INFO - Brooklyn Nets: Successfully scraped!
[2023-05-01T15:10:25.850+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:25.853+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:25.856+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:10:27.100+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:27.101+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:27.103+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:10:28.398+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:28.400+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:28.402+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:10:29.962+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:29.965+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:29.967+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:10:31.271+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:31.275+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:31.277+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:10:32.701+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:32.702+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:32.703+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:10:33.966+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:33.968+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:33.969+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:10:35.460+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:35.461+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:35.462+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:10:36.781+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:36.784+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:36.786+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T15:10:38.063+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:38.064+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:38.068+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T15:10:39.592+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:39.593+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:39.594+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T15:10:40.869+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:40.870+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:40.872+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:10:42.306+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:42.310+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:42.312+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:10:43.530+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:43.532+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:43.533+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:10:44.798+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:44.799+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:44.803+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:10:46.491+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:46.493+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:46.494+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:10:47.753+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:47.758+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:47.760+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:28:24.766+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bcbdc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-01T15:28:24.775+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bcbdc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-01T15:28:24.789+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:28:25.810+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf4f810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:25.812+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf4f810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:25.814+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:28:26.054+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-01T15:28:26.073+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5853. PIDs of all processes in the group: [5853]
[2023-05-01T15:28:26.076+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5853
[2023-05-01T15:28:26.086+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-01T15:28:26.589+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5853, status='terminated', exitcode=0, started='14:41:22') (5853) terminated with exit code 0
