[2023-05-01T22:38:12.021+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T21:30:00+00:00 [queued]>
[2023-05-01T22:38:12.067+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T21:30:00+00:00 [queued]>
[2023-05-01T22:38:12.070+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T22:38:12.071+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T22:38:12.072+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T22:38:12.123+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-01 21:30:00+00:00
[2023-05-01T22:38:12.146+0000] {standard_task_runner.py:55} INFO - Started process 10893 to run task
[2023-05-01T22:38:12.155+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-01T21:30:00+00:00', '--job-id', '2116', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp7jro7ru5']
[2023-05-01T22:38:12.165+0000] {standard_task_runner.py:83} INFO - Job 2116: Subtask scrape_teams_1-8
[2023-05-01T22:38:12.295+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T21:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T22:38:12.421+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T21:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T21:30:00+00:00
[2023-05-01T22:38:12.438+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004c750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:12.441+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004c750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:12.443+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:38:13.451+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:13.452+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:13.454+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:38:14.500+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:14.513+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:14.515+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:38:15.529+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:15.530+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:15.531+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:38:16.571+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:16.573+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:16.576+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:38:17.587+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:17.590+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:17.592+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:38:18.611+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:18.612+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:18.614+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:38:19.633+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:19.640+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:19.643+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:38:20.663+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:20.671+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:20.673+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:38:21.697+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:21.707+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:21.710+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:38:22.721+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:22.722+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:22.724+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:38:23.894+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:23.907+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:23.916+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:38:24.941+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:24.951+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:24.954+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:38:25.978+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:25.980+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:25.982+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:38:26.998+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:27.003+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:27.015+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:38:28.025+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:28.027+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:28.031+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:38:29.041+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:29.044+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:29.045+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:38:30.066+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:30.067+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:30.079+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:38:31.086+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:31.087+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:31.088+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:38:32.096+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:32.099+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:32.100+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:38:33.108+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:33.111+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:33.112+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:38:34.137+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:34.144+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:34.150+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:38:35.178+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:35.183+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:35.192+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:38:36.216+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:36.219+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:36.222+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:38:37.238+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:37.240+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:37.243+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:38:38.265+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:38.269+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:38.273+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:38:39.283+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:39.287+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:39.290+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:43:30.270+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:30.274+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:30.276+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:43:31.301+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:31.304+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:31.305+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:43:32.342+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:32.345+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:32.346+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:43:33.354+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:33.357+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:33.358+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:43:34.374+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:34.379+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:34.382+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:43:35.407+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:35.420+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:35.422+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:43:36.441+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:36.448+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:36.450+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:43:37.468+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:37.471+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:37.474+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:43:38.500+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:38.505+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:38.508+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:43:39.525+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:39.529+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:39.533+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:43:40.551+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:40.553+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:40.555+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:43:41.577+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:41.605+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:41.607+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:43:42.621+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:42.625+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:42.632+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:43:43.646+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:43.647+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:43.649+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:43:44.659+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:44.662+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:44.664+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:43:45.699+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:45.703+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:45.707+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:43:46.730+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:46.748+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:46.752+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:43:47.765+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:47.769+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:47.773+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:43:48.803+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:48.806+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:48.807+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:43:49.816+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:49.820+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:49.823+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:43:50.843+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:50.849+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:50.854+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:43:51.876+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:51.877+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:51.879+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:43:52.889+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:52.891+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005e310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:52.893+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:43:57.559+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T22:44:00.970+0000] {helpers.py:80} INFO - Chicago Bulls: Successfully scraped!
[2023-05-01T22:44:05.578+0000] {helpers.py:80} INFO - Cleveland Cavaliers: Successfully scraped!
[2023-05-01T22:44:13.897+0000] {helpers.py:80} INFO - Dallas Mavericks: Successfully scraped!
[2023-05-01T22:44:17.697+0000] {helpers.py:80} INFO - Denver Nuggets: Successfully scraped!
[2023-05-01T22:44:17.740+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_1-8.csv
[2023-05-01T22:44:17.747+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T22:44:17.778+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_1-8, execution_date=20230501T213000, start_date=20230501T223812, end_date=20230501T224417
[2023-05-01T22:44:17.947+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T22:44:17.986+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
