[2023-05-01T01:30:31.627+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-01T00:30:00+00:00 [queued]>
[2023-05-01T01:30:31.640+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-01T00:30:00+00:00 [queued]>
[2023-05-01T01:30:31.642+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T01:30:31.646+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T01:30:31.648+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T01:30:31.660+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_25-30> on 2023-05-01 00:30:00+00:00
[2023-05-01T01:30:31.667+0000] {standard_task_runner.py:55} INFO - Started process 587 to run task
[2023-05-01T01:30:31.671+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_25-30', 'scheduled__2023-05-01T00:30:00+00:00', '--job-id', '1980', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp1lthsbhg']
[2023-05-01T01:30:31.676+0000] {standard_task_runner.py:83} INFO - Job 1980: Subtask scrape_teams_25-30
[2023-05-01T01:30:31.843+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-01T00:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T01:30:31.942+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_25-30
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T00:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T00:30:00+00:00
[2023-05-01T01:30:31.956+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:31.957+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:31.960+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T01:30:32.966+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:32.968+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:32.969+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T01:30:33.974+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:33.978+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:33.980+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T01:30:34.990+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:34.993+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:34.998+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T01:30:36.007+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:36.009+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:36.010+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T01:30:37.025+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:37.027+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:37.029+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T01:30:38.038+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:38.041+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:38.045+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T01:30:39.055+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:39.057+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:39.060+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T01:30:40.071+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:40.073+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:40.078+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T01:30:41.099+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:41.103+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:41.111+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T01:30:42.118+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:42.120+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:42.121+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T01:30:43.129+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:43.131+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:43.131+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T01:30:44.139+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:44.140+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:44.141+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T01:30:45.175+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:45.178+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:45.179+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T01:30:46.189+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:46.190+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:46.192+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T01:30:47.229+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:47.235+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:47.236+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T01:30:48.249+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:48.256+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:48.258+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T01:30:49.269+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:49.270+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:49.274+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T01:30:50.282+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:50.283+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:50.286+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T01:30:51.297+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:51.300+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:51.302+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T01:30:52.312+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:52.316+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:52.321+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T01:30:53.333+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:53.335+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:53.337+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T01:30:54.351+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:54.354+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:54.356+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T01:30:55.369+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:55.373+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:55.377+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T01:30:56.386+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:56.387+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:56.390+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T01:30:57.407+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:57.415+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:57.420+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T01:30:58.433+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:58.439+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:58.443+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:01.430+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:01.432+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:01.434+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:02.448+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:02.450+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:02.451+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:03.459+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:03.461+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:03.463+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:04.469+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:04.470+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:04.471+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:05.479+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:05.483+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:05.484+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:06.492+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:06.493+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:06.494+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:07.503+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:07.505+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:07.506+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:09:08.515+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:08.524+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:08.526+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:09:09.546+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:09.551+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:09.553+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:09:10.570+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:10.582+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00535d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:10.584+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:09:11.606+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:11.613+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:11.619+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:12.633+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:12.636+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:12.640+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:13.659+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:13.663+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:13.667+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:14.679+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:14.682+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:14.683+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:15.700+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:15.706+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:15.711+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:16.724+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:16.727+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:16.731+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:17.747+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:17.751+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:17.753+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:18.772+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:18.778+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:18.782+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:09:19.816+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:19.819+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:19.824+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:09:20.855+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:20.857+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:20.859+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:09:21.878+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:21.880+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:21.884+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:09:22.900+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:22.904+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00533d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:22.906+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:23.916+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:23.919+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:23.921+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:24.928+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:24.931+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:24.933+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:25.942+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:25.944+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:25.946+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:26.955+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:26.958+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:26.959+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:27.969+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:27.971+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:27.973+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:28.980+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:28.982+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:28.983+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:29.995+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:29.996+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:29.999+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:09:31.024+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:31.027+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:31.035+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:09:32.049+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:32.053+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:32.055+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:09:33.085+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:33.088+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:33.091+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:09:34.105+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:34.106+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:34.108+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:35.115+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:35.117+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:35.118+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:36.130+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:36.136+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:36.139+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:37.158+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:37.164+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:37.170+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:38.189+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:38.193+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:38.198+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:39.212+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:39.217+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:39.219+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:40.232+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:40.244+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:40.247+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:41.655+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_25-30.csv
[2023-05-01T02:09:41.668+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T02:09:41.720+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_25-30, execution_date=20230501T003000, start_date=20230501T013031, end_date=20230501T020941
[2023-05-01T02:09:41.840+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T02:09:41.909+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
