[2023-05-01T23:44:22.840+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T22:30:00+00:00 [queued]>
[2023-05-01T23:44:22.851+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T22:30:00+00:00 [queued]>
[2023-05-01T23:44:22.854+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T23:44:22.855+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T23:44:22.857+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T23:44:22.878+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-01 22:30:00+00:00
[2023-05-01T23:44:22.886+0000] {standard_task_runner.py:55} INFO - Started process 11218 to run task
[2023-05-01T23:44:22.891+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-01T22:30:00+00:00', '--job-id', '2126', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp9o2usjpu']
[2023-05-01T23:44:22.900+0000] {standard_task_runner.py:83} INFO - Job 2126: Subtask scrape_teams_1-8
[2023-05-01T23:44:23.067+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T22:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T23:44:23.171+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T22:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T22:30:00+00:00
[2023-05-01T23:44:26.763+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T23:44:27.112+0000] {helpers.py:80} INFO - Atlanta Hawks: Successfully scraped!
[2023-05-01T23:44:36.000+0000] {helpers.py:80} INFO - Boston Celtics: Successfully scraped!
[2023-05-01T23:44:39.958+0000] {helpers.py:80} INFO - Brooklyn Nets: Successfully scraped!
[2023-05-01T23:44:44.173+0000] {helpers.py:80} INFO - Charlotte Hornets: Successfully scraped!
[2023-05-01T23:44:47.914+0000] {helpers.py:80} INFO - Chicago Bulls: Successfully scraped!
[2023-05-02T00:00:02.989+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9becc350>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-02T00:00:02.995+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9becc350>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-02T00:00:02.997+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T00:00:04.024+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bed7790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:04.030+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bed7790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:04.032+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T00:00:05.057+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9beccad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:05.082+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9beccad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:05.083+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T00:00:06.092+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9becca90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:06.094+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9becca90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:06.095+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T00:00:07.106+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9beccf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:07.109+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9beccf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T00:00:07.112+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T00:00:07.459+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T00:00:07.467+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11218. PIDs of all processes in the group: [11218]
[2023-05-02T00:00:07.468+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11218
[2023-05-02T00:00:07.470+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T00:00:07.727+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11218, status='terminated', exitcode=0, started='23:44:22') (11218) terminated with exit code 0
