[2023-04-30T17:44:32.391+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: push_to_bigquery.push_csv_to_cloud_storage scheduled__2023-04-30T16:30:00+00:00 [queued]>
[2023-04-30T17:44:32.402+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: push_to_bigquery.push_csv_to_cloud_storage scheduled__2023-04-30T16:30:00+00:00 [queued]>
[2023-04-30T17:44:32.404+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T17:44:32.405+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-30T17:44:32.407+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T17:44:32.418+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): push_csv_to_cloud_storage> on 2023-04-30 16:30:00+00:00
[2023-04-30T17:44:32.423+0000] {standard_task_runner.py:55} INFO - Started process 53 to run task
[2023-04-30T17:44:32.428+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'push_to_bigquery', 'push_csv_to_cloud_storage', 'scheduled__2023-04-30T16:30:00+00:00', '--job-id', '1916', '--raw', '--subdir', 'DAGS_FOLDER/push_to_bigquery_dag.py', '--cfg-path', '/tmp/tmp4rpz7379']
[2023-04-30T17:44:32.431+0000] {standard_task_runner.py:83} INFO - Job 1916: Subtask push_csv_to_cloud_storage
[2023-04-30T17:44:32.501+0000] {task_command.py:389} INFO - Running <TaskInstance: push_to_bigquery.push_csv_to_cloud_storage scheduled__2023-04-30T16:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-04-30T17:44:32.531+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-04-30T17:44:32.566+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=push_to_bigquery
AIRFLOW_CTX_TASK_ID=push_csv_to_cloud_storage
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T16:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T16:30:00+00:00
[2023-04-30T17:44:32.931+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/helpers.py", line 32, in push_to_gcs
    blob.upload_from_filename(source_file_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2681, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/all_teams.csv'
[2023-04-30T17:44:32.945+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=push_to_bigquery, task_id=push_csv_to_cloud_storage, execution_date=20230430T163000, start_date=20230430T174432, end_date=20230430T174432
[2023-04-30T17:44:32.954+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1916 for task push_csv_to_cloud_storage ([Errno 2] No such file or directory: '/opt/airflow/data/all_teams.csv'; 53)
[2023-04-30T17:44:32.971+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-30T17:44:32.986+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
