[2023-05-01T14:41:38.879+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T13:30:00+00:00 [queued]>
[2023-05-01T14:41:38.891+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T13:30:00+00:00 [queued]>
[2023-05-01T14:41:38.892+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T14:41:38.893+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T14:41:38.894+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T14:41:38.903+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-01 13:30:00+00:00
[2023-05-01T14:41:38.911+0000] {standard_task_runner.py:55} INFO - Started process 5873 to run task
[2023-05-01T14:41:38.916+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-01T13:30:00+00:00', '--job-id', '2057', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpumjho9eq']
[2023-05-01T14:41:38.919+0000] {standard_task_runner.py:83} INFO - Job 2057: Subtask scrape_teams_1-8
[2023-05-01T14:41:38.986+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T13:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T14:41:39.049+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T13:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T13:30:00+00:00
[2023-05-01T14:41:42.707+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T14:41:44.451+0000] {helpers.py:80} INFO - Atlanta Hawks: Successfully scraped!
[2023-05-01T15:10:25.119+0000] {helpers.py:80} INFO - Boston Celtics: Successfully scraped!
[2023-05-01T15:10:25.809+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:25.812+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:25.814+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:10:27.470+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:27.474+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:27.475+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:10:28.789+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:28.791+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:28.792+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:10:30.841+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:30.844+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:30.855+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:10:32.338+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:32.339+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:32.342+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:10:33.651+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:33.663+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:33.664+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:10:34.959+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:34.961+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:34.962+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:10:36.305+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:36.310+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:36.311+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:10:37.577+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:37.578+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:37.579+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T15:10:38.860+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:38.866+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:38.867+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T15:10:40.240+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:40.242+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:40.243+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T15:10:41.529+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:41.531+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:41.531+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:10:42.794+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:42.796+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:42.797+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:10:44.201+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:44.203+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:44.206+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:10:45.490+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:45.491+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:45.492+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:10:46.766+0000] {logging_mixin.py:137} INFO - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:46.769+0000] {helpers.py:86} ERROR - Expecting value: line 1 column 1 (char 0)
[2023-05-01T15:10:46.771+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:28:26.988+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-01T15:28:26.999+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5873. PIDs of all processes in the group: [5873]
[2023-05-01T15:28:27.000+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5873
[2023-05-01T15:28:27.002+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-01T15:28:27.007+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-01T15:28:27.008+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-01T15:28:27.009+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:28:28.456+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:28.469+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:28.471+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:28:29.893+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:29.906+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:29.908+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:28:30.935+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:30.942+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:30.949+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T15:28:31.968+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:31.972+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:31.989+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T15:28:33.005+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:33.008+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:33.012+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T15:28:34.029+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:34.031+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf537d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:34.034+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:28:35.051+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:35.054+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:35.055+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:28:36.065+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:36.067+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:36.069+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:28:37.095+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:37.097+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:37.098+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:28:38.120+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:38.126+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:38.128+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:28:39.136+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:39.138+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:39.141+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:28:40.163+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:40.169+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:40.172+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:28:41.206+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:41.207+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:41.209+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:28:42.235+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:42.238+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:42.241+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T15:28:43.268+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:43.273+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:43.275+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T15:28:44.306+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf530d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:44.309+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf530d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:44.311+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T15:28:45.341+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:45.345+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:45.347+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:28:46.361+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:46.363+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:28:46.364+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:48:40.581+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:40.586+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:40.593+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:48:41.611+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:41.613+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:41.615+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:48:42.638+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf539d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:42.640+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf539d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:42.642+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:48:43.663+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf530d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:43.665+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf530d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:43.666+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:48:44.678+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:44.680+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:44.687+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:48:45.693+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:45.695+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:45.699+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:48:46.719+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:46.721+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:46.722+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T15:48:47.728+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:47.730+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:47.731+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T15:48:48.750+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:48.752+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:48.754+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T15:48:49.769+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:49.773+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:49.775+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:48:50.781+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:50.782+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:50.783+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:48:51.793+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:51.795+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:51.797+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:48:52.806+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:52.808+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:52.809+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:48:53.828+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:53.832+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:53.837+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:48:54.857+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf539d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:54.859+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf539d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:54.860+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:48:55.876+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf530d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:55.877+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf530d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:55.879+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:48:56.886+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:56.888+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:56.890+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:49:20.059+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=5873, name='airflow task ru', status='sleeping', started='14:41:38') did not respond to SIGTERM. Trying SIGKILL
[2023-05-01T15:49:20.064+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 5873
[2023-05-01T15:49:20.121+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5873, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='14:41:38') (5873) terminated with exit code Negsignal.SIGKILL
[2023-05-01T15:49:20.123+0000] {standard_task_runner.py:170} ERROR - Job 2057 was killed before it finished (likely due to running out of memory)
