[2023-05-01T00:40:04.504+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-04-30T23:30:00+00:00 [queued]>
[2023-05-01T00:40:04.522+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-04-30T23:30:00+00:00 [queued]>
[2023-05-01T00:40:04.523+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T00:40:04.525+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T00:40:04.527+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T00:40:04.554+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-04-30 23:30:00+00:00
[2023-05-01T00:40:04.568+0000] {standard_task_runner.py:55} INFO - Started process 557 to run task
[2023-05-01T00:40:04.576+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-04-30T23:30:00+00:00', '--job-id', '1974', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpive921_r']
[2023-05-01T00:40:04.589+0000] {standard_task_runner.py:83} INFO - Job 1974: Subtask scrape_teams_9-16
[2023-05-01T00:40:04.714+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-04-30T23:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T00:40:04.787+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T23:30:00+00:00
[2023-05-01T00:40:04.803+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:04.805+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00446d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:04.806+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T00:40:05.817+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00566d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:05.819+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00566d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:05.820+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T00:40:06.827+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:06.829+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:06.830+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T00:40:07.840+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:07.841+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:07.842+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T00:40:08.849+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:08.851+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:08.852+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T00:40:09.866+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:09.868+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:09.869+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T00:40:10.876+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:10.878+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:10.880+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T00:40:11.888+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:11.889+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:11.891+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T00:40:12.910+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:12.912+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:12.914+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T00:40:13.921+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:13.923+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:13.924+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T00:40:14.941+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:14.943+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:14.944+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T00:40:15.950+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00566d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:15.953+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00566d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:15.954+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T00:40:16.961+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:16.964+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:16.965+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T00:40:17.977+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:17.979+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:17.980+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T00:40:18.986+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:18.988+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:18.989+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T00:40:19.995+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:19.996+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:19.997+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T00:40:21.004+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:21.005+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:21.006+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T00:40:22.018+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:22.020+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:22.021+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T00:40:23.030+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:23.032+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:23.034+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T00:40:24.042+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:24.044+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:24.047+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T00:40:25.056+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:25.060+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:25.062+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T00:40:26.068+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:26.069+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:26.070+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T00:40:27.085+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:27.091+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:27.093+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T00:40:28.123+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:28.129+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:28.135+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T00:40:29.150+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:29.153+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:29.156+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T00:40:30.168+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:30.171+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:30.174+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T00:40:31.185+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:31.187+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:31.189+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T00:40:32.203+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:32.207+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:32.210+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T01:30:29.911+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:29.914+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:29.917+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T01:30:30.947+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:30.956+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:30.960+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T01:30:31.969+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:31.971+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:31.972+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T01:30:32.979+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:32.981+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:32.982+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T01:30:33.989+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:33.991+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:33.992+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T01:30:35.011+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:35.013+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:35.014+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T01:30:36.023+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:36.025+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:36.026+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T01:30:37.035+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:37.037+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:37.038+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T01:30:38.046+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:38.049+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:38.051+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T01:30:39.064+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:39.065+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:39.066+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T01:30:40.078+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:40.079+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:40.081+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T01:30:41.090+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:41.095+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:41.099+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T01:30:42.110+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:42.112+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:42.114+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T01:30:43.120+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:43.122+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:43.123+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T01:30:44.131+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:44.132+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:44.133+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T01:30:45.171+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:45.175+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:45.178+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T01:30:46.197+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:46.198+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:46.201+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T01:30:47.225+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:47.231+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:47.235+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T01:30:48.251+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:48.257+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:48.258+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T01:30:49.268+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:49.271+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:49.276+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T01:30:50.285+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:50.287+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:50.288+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T01:30:51.296+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:51.298+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:51.300+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T01:30:52.313+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:52.319+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:52.321+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T01:30:53.335+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:53.339+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:53.341+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T01:30:54.352+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:54.356+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:54.357+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T01:30:55.371+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:55.373+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:55.376+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T01:30:56.386+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:56.388+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:56.390+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T01:30:57.410+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:57.413+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00564d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:57.417+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T01:30:58.430+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:58.433+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T01:30:58.440+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:09:01.441+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:01.442+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:01.443+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:09:02.450+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:02.452+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:02.454+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:09:03.462+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:03.465+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:03.466+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:04.476+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:04.477+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:04.479+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:05.485+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:05.488+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:05.489+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:06.497+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:06.498+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:06.499+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:07.507+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:07.509+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:07.511+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:08.521+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:08.523+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:08.525+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:09.547+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:09.551+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:09.555+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:10.573+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:10.582+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00565d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:10.590+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:09:11.609+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:11.614+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:11.619+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:09:12.634+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:12.636+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:12.638+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:09:13.661+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:13.664+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00562d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:13.666+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:09:14.679+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:14.683+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:14.684+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:15.701+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:15.709+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:15.714+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:16.724+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:16.725+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:16.727+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:17.746+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:17.748+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:17.750+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:18.775+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:18.781+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:18.784+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:19.815+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:19.825+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00560d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:19.827+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:20.856+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:20.857+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0056190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:20.859+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:21.877+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8d184d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:21.879+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8d184d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:21.881+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T02:09:22.894+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cfcd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:22.898+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cfcd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:22.903+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T02:09:23.927+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:23.931+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:23.933+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T02:09:24.947+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:24.949+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:24.950+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T02:09:25.960+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:25.962+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:25.964+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T02:09:26.971+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:26.973+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:26.975+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T02:09:27.985+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:27.988+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:27.990+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T02:09:28.998+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:29.000+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:29.001+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T02:09:30.008+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:30.009+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003ad50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:30.010+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T02:09:31.032+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:31.036+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:31.044+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T02:09:32.067+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:32.068+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=heat&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003a410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T02:09:32.068+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T02:09:33.104+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_9-16.csv
[2023-05-01T02:09:33.106+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T02:09:33.144+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_9-16, execution_date=20230430T233000, start_date=20230501T004004, end_date=20230501T020933
[2023-05-01T02:09:33.226+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T02:09:33.266+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
