[2023-05-11T01:25:20.100+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-11T00:00:00+00:00 [queued]>
[2023-05-11T01:25:20.129+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-11T00:00:00+00:00 [queued]>
[2023-05-11T01:25:20.130+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T01:25:20.132+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-11T01:25:20.133+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T01:25:20.150+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-11 00:00:00+00:00
[2023-05-11T01:25:20.158+0000] {standard_task_runner.py:55} INFO - Started process 28662 to run task
[2023-05-11T01:25:20.165+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-11T00:00:00+00:00', '--job-id', '4224', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_push_dag.py', '--cfg-path', '/tmp/tmpjw6q_qw1']
[2023-05-11T01:25:20.170+0000] {standard_task_runner.py:83} INFO - Job 4224: Subtask scrape_teams_1-8
[2023-05-11T01:25:20.272+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-11T00:00:00+00:00 [running]> on host f41dbfa3d325
[2023-05-11T01:25:20.315+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-11T01:25:20.372+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-11T00:00:00+00:00
[2023-05-11T01:25:20.386+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947d56d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:21.243+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947d57d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:23.419+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T01:25:23.422+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-11T01:25:24.430+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff948053d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:25.696+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:29.514+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T01:25:29.516+0000] {helpers.py:101} ERROR - Retrying! 8 attempts before skipping!
[2023-05-11T01:25:30.524+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e410>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:31.306+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:33.846+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T01:25:33.852+0000] {helpers.py:101} ERROR - Retrying! 7 attempts before skipping!
[2023-05-11T01:25:34.877+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:35.572+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947a3250>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:38.169+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478efd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T01:25:38.174+0000] {helpers.py:101} ERROR - Retrying! 6 attempts before skipping!
[2023-05-11T01:25:39.188+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:40.037+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478eb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:42.409+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T01:25:42.410+0000] {helpers.py:101} ERROR - Retrying! 5 attempts before skipping!
[2023-05-11T01:25:43.467+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:44.336+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805810>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T01:25:48.161+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947a3a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T01:25:48.163+0000] {helpers.py:101} ERROR - Retrying! 4 attempts before skipping!
[2023-05-11T02:15:05.037+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947a3e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:05.159+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947ac690>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:08.016+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b41d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:08.019+0000] {helpers.py:101} ERROR - Retrying! 3 attempts before skipping!
[2023-05-11T02:15:09.036+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff948055d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:09.569+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805690>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:12.977+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478ead0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:12.979+0000] {helpers.py:101} ERROR - Retrying! 2 attempts before skipping!
[2023-05-11T02:15:13.987+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e990>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:14.179+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478edd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:16.984+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b52d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:16.985+0000] {helpers.py:101} ERROR - Retrying! 1 attempts before skipping!
[2023-05-11T02:15:17.992+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b5090>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:18.880+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b5ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:22.479+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c1310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:22.481+0000] {helpers.py:101} ERROR - Retrying! 0 attempts before skipping!
[2023-05-11T02:15:23.492+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478ea10>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:24.382+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478ed90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:26.736+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:26.738+0000] {helpers.py:101} ERROR - Retrying! -1 attempts before skipping!
[2023-05-11T02:15:27.747+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805150>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T02:15:27.930+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947acb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T02:15:31.758+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c1150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:31.760+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-11T02:15:32.771+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c13d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:13.306+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c1ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:16.095+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c76d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:16.097+0000] {helpers.py:101} ERROR - Retrying! 8 attempts before skipping!
[2023-05-11T03:04:17.115+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff948050d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:19.071+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:22.799+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:22.800+0000] {helpers.py:101} ERROR - Retrying! 7 attempts before skipping!
[2023-05-11T03:04:23.807+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478ed90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:24.760+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:27.995+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c7710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:27.998+0000] {helpers.py:101} ERROR - Retrying! 6 attempts before skipping!
[2023-05-11T03:04:29.007+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c77d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:30.281+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9474f290>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:33.451+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9474fa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:33.452+0000] {helpers.py:101} ERROR - Retrying! 5 attempts before skipping!
[2023-05-11T03:04:34.460+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9474fa90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:35.826+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c75d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:38.886+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c7c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:38.888+0000] {helpers.py:101} ERROR - Retrying! 4 attempts before skipping!
[2023-05-11T03:04:39.916+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c7c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:40.477+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:42.800+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:21.423+0000] {helpers.py:101} ERROR - Retrying! 3 attempts before skipping!
[2023-05-11T03:55:22.431+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9478e150>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:22.894+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94805490>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:25.199+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947aced0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:25.201+0000] {helpers.py:101} ERROR - Retrying! 2 attempts before skipping!
[2023-05-11T03:55:26.211+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947aced0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:28.124+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9475b350>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:30.529+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947651d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:30.531+0000] {helpers.py:101} ERROR - Retrying! 1 attempts before skipping!
[2023-05-11T03:55:31.544+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9474f510>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:32.771+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9474f190>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:35.975+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c7e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:35.980+0000] {helpers.py:101} ERROR - Retrying! 0 attempts before skipping!
[2023-05-11T03:55:36.994+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c7710>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:38.366+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c7150>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:41.759+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c1ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:41.761+0000] {helpers.py:101} ERROR - Retrying! -1 attempts before skipping!
[2023-05-11T03:55:42.772+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c1950>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/gonets/comments/
[2023-05-11T03:55:44.556+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b5510>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/gonets/comments/
[2023-05-11T03:55:47.574+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b5d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:47.575+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-11T03:55:48.591+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b5750>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/gonets/comments/
[2023-05-11T03:55:51.163+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(ProtocolError('Connection aborted.', OSError(0, 'Error'))) status: GET https://oauth.reddit.com/r/gonets/comments/
[2023-05-11T04:34:25.330+0000] {helpers.py:95} INFO - Brooklyn Nets: Successfully scraped!
[2023-05-11T04:34:26.207+0000] {helpers.py:95} INFO - Charlotte Hornets: Successfully scraped!
[2023-05-11T04:34:27.675+0000] {helpers.py:95} INFO - Chicago Bulls: Successfully scraped!
[2023-05-11T04:34:29.306+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-11T04:34:29.434+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 28662. PIDs of all processes in the group: [28662]
[2023-05-11T04:34:29.455+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 28662
[2023-05-11T04:34:29.499+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-11T04:34:29.506+0000] {helpers.py:100} ERROR - Task received SIGTERM signal
[2023-05-11T04:34:29.514+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-11T04:34:31.671+0000] {helpers.py:95} INFO - Cleveland Cavaliers: Successfully scraped!
[2023-05-11T04:34:34.324+0000] {helpers.py:95} INFO - Dallas Mavericks: Successfully scraped!
[2023-05-11T04:51:55.597+0000] {sessions.py:161} WARNING - Retrying due to ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16.0)")) status: GET https://oauth.reddit.com/r/denvernuggets/comments/
[2023-05-11T04:52:00.194+0000] {helpers.py:95} INFO - Denver Nuggets: Successfully scraped!
[2023-05-11T04:52:00.200+0000] {helpers.py:110} INFO - Saved in /opt/***/data/output_scrape_teams_1-8.csv
[2023-05-11T04:52:00.201+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-11T04:52:00.213+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_1-8, execution_date=20230511T000000, start_date=20230511T012520, end_date=20230511T045200
[2023-05-11T04:52:00.281+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=28662, status='terminated', exitcode=0, started='01:25:20') (28662) terminated with exit code 0
