[2023-05-11T02:15:06.750+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-11T01:00:00+00:00 [queued]>
[2023-05-11T02:15:06.762+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-11T01:00:00+00:00 [queued]>
[2023-05-11T02:15:06.763+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T02:15:06.766+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-11T02:15:06.768+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T02:15:06.778+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-11 01:00:00+00:00
[2023-05-11T02:15:06.799+0000] {standard_task_runner.py:55} INFO - Started process 28684 to run task
[2023-05-11T02:15:06.805+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-11T01:00:00+00:00', '--job-id', '4228', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_push_dag.py', '--cfg-path', '/tmp/tmpgtk6ke06']
[2023-05-11T02:15:06.809+0000] {standard_task_runner.py:83} INFO - Job 4228: Subtask scrape_teams_1-8
[2023-05-11T02:15:06.899+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-11T01:00:00+00:00 [running]> on host f41dbfa3d325
[2023-05-11T02:15:06.939+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-11T02:15:06.987+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T01:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-11T01:00:00+00:00
[2023-05-11T02:15:07.025+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff948091d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:08.428+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff948092d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:11.376+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94809e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:11.378+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-11T02:15:12.387+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790050>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:12.447+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790690>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:15.159+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:15.164+0000] {helpers.py:101} ERROR - Retrying! 8 attempts before skipping!
[2023-05-11T02:15:16.169+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b310>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:18.113+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:20.623+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947a4290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:20.626+0000] {helpers.py:101} ERROR - Retrying! 7 attempts before skipping!
[2023-05-11T02:15:21.635+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947a4490>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:22.635+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947a4d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:26.000+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:26.004+0000] {helpers.py:101} ERROR - Retrying! 6 attempts before skipping!
[2023-05-11T02:15:27.011+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b190>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:27.639+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:30.759+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947904d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T02:15:30.761+0000] {helpers.py:101} ERROR - Retrying! 5 attempts before skipping!
[2023-05-11T02:15:31.770+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790810>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T02:15:33.476+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94809c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:16.170+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947ac550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:16.194+0000] {helpers.py:101} ERROR - Retrying! 4 attempts before skipping!
[2023-05-11T03:04:17.200+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947ac410>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:17.635+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947ba190>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:21.405+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947ba990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:21.407+0000] {helpers.py:101} ERROR - Retrying! 3 attempts before skipping!
[2023-05-11T03:04:22.430+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:22.534+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790210>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:24.845+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:24.847+0000] {helpers.py:101} ERROR - Retrying! 2 attempts before skipping!
[2023-05-11T03:04:25.889+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b610>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:27.220+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:30.977+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-11T03:04:30.985+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 28684. PIDs of all processes in the group: [28684]
[2023-05-11T03:04:30.986+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 28684
[2023-05-11T03:04:30.987+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-11T03:04:30.992+0000] {helpers.py:100} ERROR - Task received SIGTERM signal
[2023-05-11T03:04:30.994+0000] {helpers.py:101} ERROR - Retrying! 1 attempts before skipping!
[2023-05-11T03:04:32.006+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947badd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:33.173+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c0550>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:35.958+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947cb110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:35.959+0000] {helpers.py:101} ERROR - Retrying! 0 attempts before skipping!
[2023-05-11T03:04:36.966+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b690>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:37.603+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-11T03:04:40.392+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947906d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:04:40.394+0000] {helpers.py:101} ERROR - Retrying! -1 attempts before skipping!
[2023-05-11T03:04:41.422+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:04:42.441+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790290>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:23.231+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94809b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:23.232+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-11T03:55:24.242+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:24.675+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947cb050>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:28.380+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94753050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:28.381+0000] {helpers.py:101} ERROR - Retrying! 8 attempts before skipping!
[2023-05-11T03:55:29.387+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94753090>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:29.822+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947cb7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:32.789+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94809510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:32.790+0000] {helpers.py:101} ERROR - Retrying! 7 attempts before skipping!
[2023-05-11T03:55:33.796+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94809f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:34.852+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790590>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:38.447+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94790cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:38.449+0000] {helpers.py:101} ERROR - Retrying! 6 attempts before skipping!
[2023-05-11T03:55:39.467+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9484c410>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:39.873+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479be50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:43.802+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c0e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:43.806+0000] {helpers.py:101} ERROR - Retrying! 5 attempts before skipping!
[2023-05-11T03:55:44.811+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c0f90>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:45.237+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94753590>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T03:55:47.509+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9475f110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-11T03:55:47.511+0000] {helpers.py:101} ERROR - Retrying! 4 attempts before skipping!
[2023-05-11T03:55:48.521+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9479b550>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T04:34:34.867+0000] {sessions.py:161} WARNING - Retrying due to ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=16.0)")) status: GET https://oauth.reddit.com/r/bostonceltics/comments/
[2023-05-11T04:34:38.613+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=28684, name='airflow task ru', status='sleeping', started='02:15:05') did not respond to SIGTERM. Trying SIGKILL
[2023-05-11T04:34:38.750+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 28684
[2023-05-11T04:34:39.075+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=28684, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:15:05') (28684) terminated with exit code Negsignal.SIGKILL
[2023-05-11T04:34:39.084+0000] {standard_task_runner.py:170} ERROR - Job 4228 was killed before it finished (likely due to running out of memory)
