[2023-05-10T21:00:34.475+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-10T20:00:00+00:00 [queued]>
[2023-05-10T21:00:34.509+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-10T20:00:00+00:00 [queued]>
[2023-05-10T21:00:34.511+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-10T21:00:34.517+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-10T21:00:34.521+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-10T21:00:34.538+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-10 20:00:00+00:00
[2023-05-10T21:00:34.547+0000] {standard_task_runner.py:55} INFO - Started process 25505 to run task
[2023-05-10T21:00:34.559+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-10T20:00:00+00:00', '--job-id', '4201', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_push_dag.py', '--cfg-path', '/tmp/tmp79l6mstk']
[2023-05-10T21:00:34.571+0000] {standard_task_runner.py:83} INFO - Job 4201: Subtask scrape_teams_1-8
[2023-05-10T21:00:34.668+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-10T20:00:00+00:00 [running]> on host f41dbfa3d325
[2023-05-10T21:00:34.710+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-10T21:00:34.758+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-10T20:00:00+00:00
[2023-05-10T21:00:34.776+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b3410>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:35.813+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b3510>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:38.890+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947bc0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-10T21:00:38.894+0000] {helpers.py:101} ERROR - Retrying! 9 attempts before skipping!
[2023-05-10T21:00:39.906+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947bc350>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:40.626+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947bc910>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:44.462+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b3b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-10T21:00:44.468+0000] {helpers.py:101} ERROR - Retrying! 8 attempts before skipping!
[2023-05-10T21:00:45.501+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b3990>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:45.718+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947f6cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:49.217+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c5150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-10T21:00:49.221+0000] {helpers.py:101} ERROR - Retrying! 7 attempts before skipping!
[2023-05-10T21:00:50.232+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c5490>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:50.625+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c5e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:53.300+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947cd1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-10T21:00:53.305+0000] {helpers.py:101} ERROR - Retrying! 6 attempts before skipping!
[2023-05-10T21:00:54.316+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947cd450>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:54.468+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff94759050>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:57.763+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c5c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-10T21:00:57.766+0000] {helpers.py:101} ERROR - Retrying! 5 attempts before skipping!
[2023-05-10T21:00:58.776+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c5bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:00:59.405+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947c5650>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:01:03.190+0000] {helpers.py:100} ERROR - error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947f6f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-10T21:01:03.192+0000] {helpers.py:101} ERROR - Retrying! 4 attempts before skipping!
[2023-05-10T21:01:04.201+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b3510>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:01:04.969+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff947b3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/AtlantaHawks/comments/
[2023-05-10T21:01:10.931+0000] {helpers.py:95} INFO - Atlanta Hawks: Successfully scraped!
[2023-05-10T21:01:16.852+0000] {helpers.py:95} INFO - Boston Celtics: Successfully scraped!
[2023-05-10T21:01:17.864+0000] {helpers.py:95} INFO - Brooklyn Nets: Successfully scraped!
[2023-05-10T21:01:18.739+0000] {helpers.py:95} INFO - Charlotte Hornets: Successfully scraped!
[2023-05-10T21:01:19.569+0000] {helpers.py:95} INFO - Chicago Bulls: Successfully scraped!
[2023-05-10T21:01:20.500+0000] {helpers.py:95} INFO - Cleveland Cavaliers: Successfully scraped!
[2023-05-10T21:01:21.358+0000] {helpers.py:95} INFO - Dallas Mavericks: Successfully scraped!
[2023-05-10T21:01:25.461+0000] {helpers.py:95} INFO - Denver Nuggets: Successfully scraped!
[2023-05-10T21:01:25.471+0000] {helpers.py:110} INFO - Saved in /opt/***/data/output_scrape_teams_1-8.csv
[2023-05-10T21:01:25.475+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-10T21:01:25.488+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_1-8, execution_date=20230510T200000, start_date=20230510T210034, end_date=20230510T210125
[2023-05-10T21:01:25.515+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-10T21:01:25.540+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
