[2023-04-30T20:03:47.354+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-04-30T18:30:00+00:00 [queued]>
[2023-04-30T20:03:47.366+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-04-30T18:30:00+00:00 [queued]>
[2023-04-30T20:03:47.367+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T20:03:47.370+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-30T20:03:47.371+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T20:03:47.389+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_25-30> on 2023-04-30 18:30:00+00:00
[2023-04-30T20:03:47.398+0000] {standard_task_runner.py:55} INFO - Started process 383 to run task
[2023-04-30T20:03:47.405+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_25-30', 'scheduled__2023-04-30T18:30:00+00:00', '--job-id', '1943', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpwvy2bame']
[2023-04-30T20:03:47.409+0000] {standard_task_runner.py:83} INFO - Job 1943: Subtask scrape_teams_25-30
[2023-04-30T20:03:47.536+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-04-30T18:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-04-30T20:03:47.667+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_25-30
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T18:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T18:30:00+00:00
[2023-04-30T20:03:47.678+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:47.680+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:47.681+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:03:48.689+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:48.690+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:48.691+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:03:49.698+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:49.701+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:49.702+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:03:50.721+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:50.723+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:50.725+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:03:51.745+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:51.749+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:51.752+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:03:52.760+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:52.761+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:52.762+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:03:53.772+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:53.773+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:53.777+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:03:54.785+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:54.787+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:54.788+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:03:55.796+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:55.798+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:55.799+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:03:56.809+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:56.811+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:56.813+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:03:57.825+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:57.826+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:57.828+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:03:58.850+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:58.856+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:58.857+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:03:59.866+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:59.867+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:03:59.869+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:04:00.895+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:00.903+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:00.907+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:04:01.918+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:01.920+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:01.921+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:04:02.938+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:02.940+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:02.942+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:04:03.961+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:03.968+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:03.970+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:04:04.991+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:04.996+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:05.000+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:04:06.021+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:06.023+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:06.025+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:04:07.098+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:07.175+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:07.178+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:04:08.215+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:08.219+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:08.225+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:04:09.268+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:09.270+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:09.272+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:04:10.296+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:10.303+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:10.307+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:04:11.343+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:11.352+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:11.355+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:04:12.371+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:12.372+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:12.376+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:04:13.402+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:13.410+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:13.413+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:04:14.428+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:14.432+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:04:14.434+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:38:49.466+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:49.471+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:49.474+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:38:50.486+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:50.487+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:50.489+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:38:51.501+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:51.502+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:51.505+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:38:52.519+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:52.522+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:52.524+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:38:53.555+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:53.568+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:53.571+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:38:54.599+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:54.604+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:54.606+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:38:55.631+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:55.636+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:55.642+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:38:56.658+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:56.661+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:56.662+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:38:57.673+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:57.676+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:57.678+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:38:58.701+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:58.708+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:58.709+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:38:59.741+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:59.748+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:38:59.750+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:39:00.761+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:00.763+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:00.767+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:39:01.778+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:01.780+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:01.782+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:39:02.796+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:02.800+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:02.801+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:39:03.814+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:03.816+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:03.818+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:39:04.838+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:04.843+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:04.845+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:39:05.863+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:05.871+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:05.875+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:39:06.900+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:06.904+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:06.909+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:39:07.924+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:07.927+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:07.929+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T20:39:08.946+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:08.950+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:08.954+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T20:39:09.981+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:09.989+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:09.997+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T20:39:11.035+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:11.041+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:11.046+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T20:39:12.062+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:12.064+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:12.067+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T20:39:13.098+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:13.100+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:13.102+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T20:39:14.111+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:14.113+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:14.117+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T20:39:15.125+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:15.127+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:15.128+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T20:39:16.140+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:16.142+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:16.143+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T20:39:17.154+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:17.157+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:17.158+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T20:39:18.184+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:18.192+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:18.199+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T20:39:19.238+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:19.239+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T20:39:19.242+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T21:23:09.040+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:09.043+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:09.046+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T21:23:10.065+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:10.067+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:10.068+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T21:23:11.077+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:11.078+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:11.079+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T21:23:12.099+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:12.101+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:12.104+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T21:23:13.115+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:13.118+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:13.119+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T21:23:14.128+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:14.130+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:14.131+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T21:23:15.139+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:15.143+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ab90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:15.147+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T21:23:16.155+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:16.156+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:16.159+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T21:23:17.183+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:17.186+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T21:23:17.191+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T21:23:18.282+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_25-30.csv
[2023-04-30T21:23:18.286+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-30T21:23:18.378+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_25-30, execution_date=20230430T183000, start_date=20230430T200347, end_date=20230430T212318
[2023-04-30T21:23:18.465+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-30T21:23:18.517+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
