[2023-05-02T00:31:52.025+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-01T23:30:00+00:00 [queued]>
[2023-05-02T00:31:52.038+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-01T23:30:00+00:00 [queued]>
[2023-05-02T00:31:52.043+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T00:31:52.044+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T00:31:52.047+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T00:31:52.094+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_25-30> on 2023-05-01 23:30:00+00:00
[2023-05-02T00:31:52.102+0000] {standard_task_runner.py:55} INFO - Started process 11262 to run task
[2023-05-02T00:31:52.107+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_25-30', 'scheduled__2023-05-01T23:30:00+00:00', '--job-id', '2131', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpr7gtxnk3']
[2023-05-02T00:31:52.127+0000] {standard_task_runner.py:83} INFO - Job 2131: Subtask scrape_teams_25-30
[2023-05-02T00:31:52.271+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-05-01T23:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-02T00:31:52.479+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_25-30
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T23:30:00+00:00
[2023-05-02T00:31:55.267+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-02T00:31:55.621+0000] {helpers.py:80} INFO - Portland Trail Blazers: Successfully scraped!
[2023-05-02T01:52:53.839+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T01:52:53.862+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11262. PIDs of all processes in the group: [11262]
[2023-05-02T01:52:53.867+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11262
[2023-05-02T01:52:53.872+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T01:52:53.886+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-02T01:52:53.888+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-02T01:52:53.890+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T01:52:54.910+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:54.915+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:54.923+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T01:52:55.948+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:55.951+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:55.952+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T01:52:56.965+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:56.969+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:56.970+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T01:52:57.984+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf538d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:57.986+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf538d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:57.990+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T01:52:59.009+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:59.010+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:59.012+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T01:53:00.025+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:00.028+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:00.034+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T01:53:01.049+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:01.051+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:01.054+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T01:53:02.064+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:02.065+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:02.067+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T01:53:03.077+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:03.078+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:03.080+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T01:53:04.087+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:04.089+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:04.090+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T01:53:05.106+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:05.111+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:05.115+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T01:53:06.124+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:06.125+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:06.126+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T01:53:07.180+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:07.277+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:07.282+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T01:53:08.302+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:08.305+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:08.307+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T01:53:09.320+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:09.334+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:09.337+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T01:53:10.347+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:10.348+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:10.350+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T01:53:11.366+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:11.368+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:11.369+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T01:53:12.377+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:12.378+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:12.379+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T01:53:13.391+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:13.393+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:13.396+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T01:53:14.407+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf538d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:14.411+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf538d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:14.413+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:25:37.111+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:37.115+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:37.118+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:25:38.130+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:38.134+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:38.136+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:25:39.144+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:39.146+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:39.147+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:25:40.294+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:40.349+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:40.361+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:25:41.379+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:41.381+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:41.383+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:25:42.414+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:42.419+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:42.422+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:25:43.444+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:43.448+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:43.452+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T02:25:44.476+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:44.478+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:44.488+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T02:25:45.526+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:45.535+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:45.540+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T02:25:46.584+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:46.599+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:46.618+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T02:25:47.645+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:47.646+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:47.648+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:25:48.658+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:48.664+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:48.667+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:25:49.674+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:49.675+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:49.678+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:25:50.683+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:50.685+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:50.685+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:25:51.801+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:51.803+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:51.804+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:25:52.837+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:52.841+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:52.860+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:25:53.869+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:53.871+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:53.872+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:25:54.901+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:54.916+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:54.919+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T02:25:55.944+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:55.951+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:55.954+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T02:25:56.984+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:56.994+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:56.997+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T02:25:58.034+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:58.039+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:58.041+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T02:25:59.066+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:59.068+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:59.072+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:26:00.094+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:00.103+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:00.105+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:26:01.138+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:01.159+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:01.162+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:26:02.186+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:02.195+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:02.201+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:26:03.253+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:03.256+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:03.257+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:26:04.282+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:04.286+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:04.289+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:26:05.313+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:05.320+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:05.332+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:26:06.350+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:06.352+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:06.353+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T03:16:33.980+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:33.983+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:33.984+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T03:16:34.994+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.006+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.011+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T03:16:36.019+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.021+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.022+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T03:16:37.030+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf534d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.034+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf534d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.036+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T03:16:38.047+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.050+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf53810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.051+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T03:16:39.088+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_25-30.csv
[2023-05-02T03:16:39.094+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-02T03:16:39.121+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_25-30, execution_date=20230501T233000, start_date=20230502T003152, end_date=20230502T031639
[2023-05-02T03:16:39.189+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11262, status='terminated', exitcode=0, started='00:31:51') (11262) terminated with exit code 0
