[2023-05-02T00:31:51.929+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T23:30:00+00:00 [queued]>
[2023-05-02T00:31:51.951+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T23:30:00+00:00 [queued]>
[2023-05-02T00:31:51.953+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T00:31:51.955+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T00:31:51.958+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T00:31:52.014+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-01 23:30:00+00:00
[2023-05-02T00:31:52.021+0000] {standard_task_runner.py:55} INFO - Started process 11260 to run task
[2023-05-02T00:31:52.037+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-01T23:30:00+00:00', '--job-id', '2129', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpergbg01i']
[2023-05-02T00:31:52.040+0000] {standard_task_runner.py:83} INFO - Job 2129: Subtask scrape_teams_9-16
[2023-05-02T00:31:52.222+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T23:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-02T00:31:52.401+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T23:30:00+00:00
[2023-05-02T00:31:55.062+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-02T00:31:55.455+0000] {helpers.py:80} INFO - Detroit Pistons: Successfully scraped!
[2023-05-02T01:52:53.844+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T01:52:53.862+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11260. PIDs of all processes in the group: [11260]
[2023-05-02T01:52:53.867+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11260
[2023-05-02T01:52:53.872+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T01:52:53.886+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-02T01:52:53.888+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-02T01:52:53.890+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T01:52:54.910+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:54.915+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:54.920+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T01:52:55.949+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc30d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:55.951+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc30d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:55.952+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T01:52:56.962+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:56.963+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:56.966+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T01:52:57.980+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:57.982+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:57.983+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T01:52:58.994+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:58.997+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:59.007+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T01:53:00.027+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:00.029+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:00.035+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T01:53:01.049+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:01.052+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:01.053+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T01:53:02.063+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:02.065+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:02.067+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T01:53:03.078+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:03.080+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:03.081+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T01:53:04.090+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:04.091+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:04.093+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T01:53:05.103+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:05.107+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:05.109+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T01:53:06.123+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:06.124+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:06.125+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T01:53:07.180+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc33d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:07.276+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc33d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:07.281+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T01:53:08.301+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:08.305+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:08.307+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T01:53:09.323+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:09.334+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:09.337+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T01:53:10.347+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:10.348+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:10.351+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T01:53:11.369+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:11.370+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:11.371+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T01:53:12.378+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:12.379+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:12.380+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T01:53:13.390+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:13.394+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:13.395+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T01:53:14.406+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:14.411+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:14.413+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:25:37.111+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:37.113+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:37.118+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:25:38.129+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:38.134+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:38.135+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:25:39.143+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:39.146+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:39.147+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:25:40.294+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:40.349+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:40.361+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:25:41.379+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:41.381+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:41.383+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:25:42.414+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:42.419+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:42.422+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:25:43.446+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:43.449+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:43.455+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T02:25:44.476+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:44.478+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:44.488+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T02:25:45.535+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:45.545+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:45.547+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T02:25:46.578+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:46.582+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:46.600+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T02:25:47.629+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc30d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:47.631+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc30d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:47.633+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:25:48.644+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:48.646+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:48.650+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:25:49.657+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:49.658+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:49.660+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:25:50.674+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:50.675+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:50.676+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:25:51.802+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:51.803+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:51.804+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:25:52.829+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:52.837+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:52.848+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:25:53.867+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:53.869+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:53.871+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:25:54.901+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:54.916+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:54.919+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T02:25:55.943+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:55.947+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:55.950+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T02:25:56.982+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:56.990+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:56.994+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T02:25:58.027+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:58.031+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:58.033+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T02:25:59.062+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc33d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:59.065+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc33d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:59.068+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:26:00.093+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:00.097+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:00.104+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:26:01.141+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cf3e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:01.159+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cf3e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:01.161+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:26:02.191+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:02.195+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:02.199+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:26:03.254+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:03.256+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:03.257+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:26:04.282+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:04.286+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:04.290+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:26:05.312+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:05.322+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:05.332+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:26:06.349+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:06.352+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:06.353+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T03:16:33.963+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:33.973+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:33.978+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T03:16:35.008+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.010+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.011+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T03:16:36.021+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.022+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.023+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T03:16:37.030+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.032+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.034+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T03:16:38.045+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.050+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.052+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T03:16:39.062+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:39.064+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:39.065+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T03:16:40.075+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:40.077+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:40.082+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T03:16:41.091+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:41.092+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:41.094+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T03:16:42.105+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:42.108+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=memphisgrizzlies&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bbc3d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:42.109+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T03:16:42.195+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=11260, name='airflow task ru', status='sleeping', started='00:31:51') did not respond to SIGTERM. Trying SIGKILL
[2023-05-02T03:16:42.211+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 11260
[2023-05-02T03:16:42.241+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11260, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:31:51') (11260) terminated with exit code Negsignal.SIGKILL
[2023-05-02T03:16:42.244+0000] {standard_task_runner.py:170} ERROR - Job 2129 was killed before it finished (likely due to running out of memory)
