[2023-05-01T08:37:09.724+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T07:30:00+00:00 [queued]>
[2023-05-01T08:37:09.741+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T07:30:00+00:00 [queued]>
[2023-05-01T08:37:09.743+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T08:37:09.744+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T08:37:09.745+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T08:37:09.768+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-01 07:30:00+00:00
[2023-05-01T08:37:09.777+0000] {standard_task_runner.py:55} INFO - Started process 5709 to run task
[2023-05-01T08:37:09.791+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-01T07:30:00+00:00', '--job-id', '2026', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmplh0m9pnm']
[2023-05-01T08:37:09.806+0000] {standard_task_runner.py:83} INFO - Job 2026: Subtask scrape_teams_9-16
[2023-05-01T08:37:09.943+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T07:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T08:37:10.063+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T07:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T07:30:00+00:00
[2023-05-01T08:37:10.075+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:10.079+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0044090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:10.082+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T08:37:11.092+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:11.095+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:11.097+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T08:37:12.112+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:12.115+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:12.117+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T08:37:13.131+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:13.133+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:13.135+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T08:37:14.144+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:14.148+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:14.150+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T08:37:15.157+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:15.159+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:15.162+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T08:37:16.172+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:16.174+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:16.177+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T08:37:17.185+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:17.187+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:17.189+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T08:37:18.198+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:18.202+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:18.203+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T08:37:19.216+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:19.217+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:19.219+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T08:37:20.233+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:20.235+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:20.237+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T08:37:21.253+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:21.258+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:21.260+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T08:37:22.278+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:22.280+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:22.281+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T08:37:23.299+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:23.303+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:23.305+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T08:37:24.313+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:24.315+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:24.316+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T08:37:25.328+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:25.331+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:25.334+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T08:37:26.353+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:26.359+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:26.361+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T08:37:27.379+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:27.383+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:27.387+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T08:37:28.399+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:28.401+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:28.403+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T08:37:29.416+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:29.420+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:29.423+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T08:37:30.440+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:30.443+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:30.444+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T08:37:31.458+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:31.460+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:31.462+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T08:37:32.597+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:32.602+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:32.604+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T08:37:33.626+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:33.633+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:33.636+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T08:37:34.656+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:34.658+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:34.661+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T08:37:35.676+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:35.680+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:35.687+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T08:37:36.696+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:36.698+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T08:37:36.701+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T09:42:21.860+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:21.870+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:21.874+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T09:42:22.890+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:22.892+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:22.893+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T09:42:23.917+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:23.920+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:23.930+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T09:42:24.944+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:24.945+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:24.946+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T09:42:25.953+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:25.956+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:25.957+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T09:42:26.966+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:26.968+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:26.970+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T09:42:27.986+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:27.996+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:27.999+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T09:42:29.008+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:29.011+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:29.013+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T09:42:30.027+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:30.032+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:30.034+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T09:42:31.054+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:31.058+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:31.061+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T09:42:32.083+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:32.087+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:32.092+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T09:42:33.117+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:33.126+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:33.131+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T09:42:34.143+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:34.146+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:34.148+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T09:42:35.164+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:35.167+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:35.169+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T09:42:36.188+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:36.191+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:36.194+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T09:42:37.202+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:37.203+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:37.204+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T09:42:38.219+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:38.225+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:38.227+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T09:42:39.252+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:39.255+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:39.258+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T09:42:40.267+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:40.269+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:40.270+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T09:42:41.288+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:41.289+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:41.292+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T09:42:42.343+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:42.345+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:42.350+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T09:42:43.367+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:43.370+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:43.372+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T09:42:44.383+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:44.385+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:44.386+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T09:42:45.402+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:45.405+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:45.407+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T09:42:46.424+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:46.426+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:46.428+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T09:42:47.523+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:47.528+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:47.529+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T09:42:48.550+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:48.552+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:48.554+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T09:42:49.564+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:49.565+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:49.566+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T09:42:50.573+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:50.575+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T09:42:50.577+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T10:48:53.705+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:53.707+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:53.712+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T10:48:54.723+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:54.725+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:54.726+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T10:48:55.746+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:55.749+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:55.754+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T10:48:56.765+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:56.767+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:56.768+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T10:48:57.784+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:57.785+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:57.787+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T10:48:58.796+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:58.799+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:58.802+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T10:48:59.812+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:59.813+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:48:59.815+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T10:49:00.823+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:00.824+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=lakers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004d110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T10:49:00.825+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T10:49:01.709+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-01T10:49:01.718+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5709. PIDs of all processes in the group: [5709]
[2023-05-01T10:49:01.719+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5709
[2023-05-01T10:49:01.722+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-01T10:49:01.828+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5709, status='terminated', exitcode=0, started='08:37:09') (5709) terminated with exit code 0
