[2023-04-30T22:30:11.308+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-04-30T21:30:00+00:00 [queued]>
[2023-04-30T22:30:11.323+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-04-30T21:30:00+00:00 [queued]>
[2023-04-30T22:30:11.326+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T22:30:11.327+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-30T22:30:11.328+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T22:30:11.352+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_25-30> on 2023-04-30 21:30:00+00:00
[2023-04-30T22:30:11.359+0000] {standard_task_runner.py:55} INFO - Started process 480 to run task
[2023-04-30T22:30:11.374+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_25-30', 'scheduled__2023-04-30T21:30:00+00:00', '--job-id', '1959', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpieq9aeua']
[2023-04-30T22:30:11.378+0000] {standard_task_runner.py:83} INFO - Job 1959: Subtask scrape_teams_25-30
[2023-04-30T22:30:11.485+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_25-30 scheduled__2023-04-30T21:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-04-30T22:30:11.599+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_25-30
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T21:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T21:30:00+00:00
[2023-04-30T22:30:11.620+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:11.622+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:11.625+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T22:30:12.632+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:12.633+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:12.636+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T22:30:13.650+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:13.654+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:13.656+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T22:30:15.236+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:15.242+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:15.253+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T22:30:16.268+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:16.273+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:16.276+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T22:30:17.302+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:17.305+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:17.306+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T22:30:18.332+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:18.338+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:18.341+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T22:30:19.363+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:19.371+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:19.376+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T22:30:20.395+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:20.399+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:20.402+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T22:30:21.431+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:21.439+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:21.446+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T22:30:22.467+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:22.471+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=ripcity&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:22.473+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T22:30:23.501+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:23.506+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:23.507+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T22:30:24.520+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:24.541+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:24.549+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T22:30:25.564+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:25.567+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:25.573+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T22:30:26.697+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:26.699+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:26.704+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T22:30:27.719+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:27.721+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:27.723+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T22:30:28.736+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:28.743+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:28.744+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T22:30:29.756+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:29.758+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:29.760+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T22:30:30.778+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:30.788+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:30.791+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T22:30:31.806+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:31.811+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:31.812+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T22:30:32.827+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:32.834+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa00531d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:32.840+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T22:30:33.853+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:33.856+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=kings&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:33.859+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T22:30:34.870+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:34.872+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:34.874+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T22:30:35.887+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:35.893+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:35.897+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T22:30:36.908+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:36.910+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:36.912+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T22:30:37.953+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:38.028+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:38.031+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T22:30:39.062+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:39.068+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:39.070+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:19:46.867+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:46.876+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:46.881+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:19:47.903+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:47.905+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:47.907+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:19:48.919+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:48.920+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:48.923+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:19:49.948+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:49.953+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:49.954+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:19:50.967+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:50.970+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:50.974+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:19:52.001+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:52.010+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=NBASpurs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:52.014+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:19:53.043+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:53.053+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:53.055+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:19:54.068+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:54.072+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:54.075+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:19:55.110+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:55.113+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:55.115+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:19:56.131+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:56.138+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:56.142+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:19:57.154+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:57.160+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:57.166+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:19:58.174+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:58.180+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:58.183+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:19:59.209+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:59.217+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:59.222+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:20:00.239+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:00.244+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:00.246+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:20:01.266+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:01.272+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:01.274+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:20:02.300+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:02.303+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:02.307+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:20:03.330+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:03.337+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=torontoraptors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:03.338+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:20:04.354+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:04.358+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:04.361+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:20:05.373+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:05.375+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:05.376+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:20:06.389+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:06.392+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:06.395+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:20:07.424+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:07.430+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:07.438+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:20:08.462+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:08.465+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:08.471+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:20:09.492+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:09.496+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:09.499+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:20:10.511+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:10.517+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:10.520+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:20:11.547+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:11.549+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:11.554+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:20:12.567+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:12.574+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:12.576+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:20:13.601+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:13.608+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:13.610+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:20:14.620+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:14.622+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=UtahJazz&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:14.623+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:20:15.639+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:15.645+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:15.649+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:51:43.317+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:43.321+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:43.325+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:51:44.337+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:44.339+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:44.342+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:51:45.359+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:45.362+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:45.364+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:51:46.378+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:46.381+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:46.385+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:51:47.393+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:47.395+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:47.398+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:51:48.422+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:48.428+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:48.429+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:51:49.440+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:49.443+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:49.445+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:51:50.461+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:50.464+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:50.466+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:51:51.474+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:51.476+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:51.477+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:51:52.485+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:52.486+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=washingtonwizards&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:52.490+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:51:53.513+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_25-30.csv
[2023-04-30T23:51:53.517+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-30T23:51:53.545+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_25-30, execution_date=20230430T213000, start_date=20230430T223011, end_date=20230430T235153
[2023-04-30T23:51:53.585+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-30T23:51:53.609+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
