[2023-05-02T03:16:35.641+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-02T01:30:00+00:00 [queued]>
[2023-05-02T03:16:35.655+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-02T01:30:00+00:00 [queued]>
[2023-05-02T03:16:35.656+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T03:16:35.660+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T03:16:35.661+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T03:16:35.678+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-02 01:30:00+00:00
[2023-05-02T03:16:35.686+0000] {standard_task_runner.py:55} INFO - Started process 11342 to run task
[2023-05-02T03:16:35.692+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-02T01:30:00+00:00', '--job-id', '2143', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp4osy6tg8']
[2023-05-02T03:16:35.698+0000] {standard_task_runner.py:83} INFO - Job 2143: Subtask scrape_teams_9-16
[2023-05-02T03:16:35.815+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-02T01:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-02T03:16:35.877+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T01:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T01:30:00+00:00
[2023-05-02T03:16:35.886+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.887+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.888+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T03:16:36.898+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003dd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.902+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa003dd50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.903+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T03:16:37.913+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.920+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.921+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T03:16:38.929+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.941+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.942+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T03:16:39.950+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:39.953+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:39.955+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T03:16:40.971+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:40.972+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:40.973+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T03:16:41.983+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:41.991+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:41.993+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T03:16:43.000+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:43.001+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:43.002+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T03:16:44.011+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004af90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:44.025+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004af90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:44.027+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T03:16:45.036+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:45.042+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:45.044+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T03:16:46.051+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:46.052+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:46.053+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T03:16:47.079+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:47.102+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:47.103+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T03:16:48.112+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004afd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:48.113+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004afd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:48.114+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T03:16:49.138+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:49.140+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:49.143+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T03:16:50.163+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:50.167+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:50.170+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T03:16:51.187+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ac90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:51.190+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004ac90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:51.195+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T03:16:52.229+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:52.236+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:52.238+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T03:16:59.340+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-02T03:17:00.177+0000] {helpers.py:80} INFO - Golden State Warriors: Successfully scraped!
[2023-05-02T03:46:11.164+0000] {helpers.py:80} INFO - Houston Rockets: Successfully scraped!
[2023-05-02T03:46:35.594+0000] {helpers.py:80} INFO - Indiana Pacers: Successfully scraped!
[2023-05-02T03:46:50.296+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T03:46:50.391+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11342. PIDs of all processes in the group: [11342]
[2023-05-02T03:46:50.544+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11342
[2023-05-02T03:46:50.763+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T03:46:50.887+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-02T03:46:50.910+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-02T03:46:50.961+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T03:46:56.304+0000] {helpers.py:80} INFO - Los Angeles Clippers: Successfully scraped!
[2023-05-02T03:47:01.910+0000] {helpers.py:80} INFO - Los Angeles Lakers: Successfully scraped!
[2023-05-02T03:47:05.726+0000] {helpers.py:80} INFO - Memphis Grizzlies: Successfully scraped!
[2023-05-02T04:19:04.229+0000] {helpers.py:80} INFO - Miami Heat: Successfully scraped!
[2023-05-02T04:19:04.264+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_9-16.csv
[2023-05-02T04:19:04.268+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-02T04:19:04.295+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_9-16, execution_date=20230502T013000, start_date=20230502T031635, end_date=20230502T041904
[2023-05-02T04:19:04.426+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11342, status='terminated', exitcode=0, started='03:16:34') (11342) terminated with exit code 0
