[2023-05-01T15:48:43.006+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T14:30:00+00:00 [queued]>
[2023-05-01T15:48:43.016+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T14:30:00+00:00 [queued]>
[2023-05-01T15:48:43.021+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T15:48:43.022+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T15:48:43.024+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T15:48:43.044+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-01 14:30:00+00:00
[2023-05-01T15:48:43.050+0000] {standard_task_runner.py:55} INFO - Started process 5916 to run task
[2023-05-01T15:48:43.057+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-01T14:30:00+00:00', '--job-id', '2062', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp33gau3df']
[2023-05-01T15:48:43.080+0000] {standard_task_runner.py:83} INFO - Job 2062: Subtask scrape_teams_9-16
[2023-05-01T15:48:43.196+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T14:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T15:48:43.308+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T14:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T14:30:00+00:00
[2023-05-01T15:48:43.323+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:43.325+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0052390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:43.326+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:48:44.336+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:44.337+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:44.338+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:48:45.354+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:45.356+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:45.357+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:48:46.377+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:46.382+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:46.385+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T15:48:47.410+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:47.414+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:47.415+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T15:48:48.427+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:48.429+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:48.430+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T15:48:49.455+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:49.457+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:49.464+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T15:48:50.492+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:50.496+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:50.496+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T15:48:51.523+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:51.526+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:51.536+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T15:48:52.565+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:52.567+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:52.568+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T15:48:53.598+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:53.605+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:53.608+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T15:48:54.630+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:54.642+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:54.645+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T15:48:55.664+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:55.670+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:55.673+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T15:48:56.681+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:56.684+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005c450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T15:48:56.688+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T15:49:00.727+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T15:49:01.540+0000] {helpers.py:80} INFO - Golden State Warriors: Successfully scraped!
[2023-05-01T15:49:07.511+0000] {helpers.py:80} INFO - Houston Rockets: Successfully scraped!
[2023-05-01T15:49:10.662+0000] {helpers.py:80} INFO - Indiana Pacers: Successfully scraped!
[2023-05-01T15:49:15.651+0000] {helpers.py:80} INFO - Los Angeles Clippers: Successfully scraped!
[2023-05-01T15:49:20.039+0000] {helpers.py:80} INFO - Los Angeles Lakers: Successfully scraped!
[2023-05-01T15:49:23.200+0000] {helpers.py:80} INFO - Memphis Grizzlies: Successfully scraped!
[2023-05-01T15:49:26.053+0000] {helpers.py:80} INFO - Miami Heat: Successfully scraped!
[2023-05-01T15:49:26.075+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_9-16.csv
[2023-05-01T15:49:26.082+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T15:49:26.094+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_9-16, execution_date=20230501T143000, start_date=20230501T154843, end_date=20230501T154926
[2023-05-01T15:49:26.150+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T15:49:26.171+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
