[2023-05-01T22:38:12.233+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T21:30:00+00:00 [queued]>
[2023-05-01T22:38:12.245+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T21:30:00+00:00 [queued]>
[2023-05-01T22:38:12.257+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T22:38:12.258+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-01T22:38:12.259+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T22:38:12.285+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_9-16> on 2023-05-01 21:30:00+00:00
[2023-05-01T22:38:12.297+0000] {standard_task_runner.py:55} INFO - Started process 10895 to run task
[2023-05-01T22:38:12.305+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_9-16', 'scheduled__2023-05-01T21:30:00+00:00', '--job-id', '2117', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp84fjggbr']
[2023-05-01T22:38:12.309+0000] {standard_task_runner.py:83} INFO - Job 2117: Subtask scrape_teams_9-16
[2023-05-01T22:38:12.441+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_9-16 scheduled__2023-05-01T21:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-01T22:38:12.525+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_9-16
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T21:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T21:30:00+00:00
[2023-05-01T22:38:12.538+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004c7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:12.540+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa004c7d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:12.541+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:38:13.550+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:13.554+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:13.557+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:38:14.594+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:14.612+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:14.617+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:38:15.637+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:15.640+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:15.644+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:38:16.723+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:16.744+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:16.778+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:38:17.805+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:17.817+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:17.820+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:38:18.831+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:18.837+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:18.840+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:38:19.861+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:19.864+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:19.866+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:38:20.877+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:20.883+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:20.892+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:38:21.904+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:21.906+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:21.907+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:38:23.897+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:23.902+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=DetroitPistons&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:23.906+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:38:24.944+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:24.955+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a350>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:24.959+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:38:25.978+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:25.982+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:25.984+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:38:26.998+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:27.003+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:27.015+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:38:28.026+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:28.028+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:28.031+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:38:29.040+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:29.043+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:29.048+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:38:30.058+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:30.061+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:30.063+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:38:31.077+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:31.078+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:31.080+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:38:32.090+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:32.092+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:32.094+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:38:33.107+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:33.109+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:33.111+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:38:34.142+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:34.150+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:34.153+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:38:35.186+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:35.192+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=warriors&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:35.194+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:38:36.218+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:36.221+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:36.229+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:38:37.240+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:37.244+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:37.246+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:38:38.272+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:38.275+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:38.278+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:38:39.290+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:39.294+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:38:39.297+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:43:30.277+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:30.278+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:30.281+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:43:31.300+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:31.303+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:31.305+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:43:32.329+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:32.338+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:32.339+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:43:33.348+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:33.349+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:33.352+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:43:34.370+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:34.376+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:34.379+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:43:35.401+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:35.405+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:35.420+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:43:36.444+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:36.447+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=rockets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:36.450+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:43:37.469+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:37.471+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:37.476+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:43:38.501+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:38.508+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:38.511+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:43:39.527+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:39.530+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:39.532+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:43:40.548+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:40.551+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:40.553+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:43:41.578+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:41.600+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:41.604+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:43:42.623+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:42.632+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005aad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:42.640+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-01T22:43:43.652+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:43.654+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:43.655+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-01T22:43:44.664+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:44.665+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:44.667+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T22:43:45.701+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:45.704+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:45.707+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T22:43:46.733+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:46.750+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:46.753+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T22:43:47.766+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:47.774+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=pacers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:47.776+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T22:43:48.803+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:48.808+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:48.809+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-01T22:43:49.821+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:49.824+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:49.828+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-01T22:43:50.855+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:50.857+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:50.858+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-01T22:43:51.878+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:51.880+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:51.882+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-01T22:43:52.891+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:52.893+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=LAClippers&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa005a210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T22:43:52.894+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-01T22:43:58.014+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-01T22:44:01.194+0000] {helpers.py:80} INFO - Los Angeles Clippers: Successfully scraped!
[2023-05-01T22:44:06.092+0000] {helpers.py:80} INFO - Los Angeles Lakers: Successfully scraped!
[2023-05-01T22:44:13.898+0000] {helpers.py:80} INFO - Memphis Grizzlies: Successfully scraped!
[2023-05-01T22:44:17.116+0000] {helpers.py:80} INFO - Miami Heat: Successfully scraped!
[2023-05-01T22:44:17.133+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_9-16.csv
[2023-05-01T22:44:17.138+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T22:44:17.156+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_9-16, execution_date=20230501T213000, start_date=20230501T223812, end_date=20230501T224417
[2023-05-01T22:44:17.299+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T22:44:17.333+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
