[2023-05-02T00:31:52.004+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T23:30:00+00:00 [queued]>
[2023-05-02T00:31:52.027+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T23:30:00+00:00 [queued]>
[2023-05-02T00:31:52.029+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T00:31:52.031+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T00:31:52.032+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T00:31:52.064+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-05-01 23:30:00+00:00
[2023-05-02T00:31:52.080+0000] {standard_task_runner.py:55} INFO - Started process 11261 to run task
[2023-05-02T00:31:52.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-05-01T23:30:00+00:00', '--job-id', '2130', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmpq80365mf']
[2023-05-02T00:31:52.095+0000] {standard_task_runner.py:83} INFO - Job 2130: Subtask scrape_teams_1-8
[2023-05-02T00:31:52.256+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-05-01T23:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-05-02T00:31:52.424+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T23:30:00+00:00
[2023-05-02T00:31:56.241+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:313: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-05-02T00:31:56.579+0000] {helpers.py:80} INFO - Atlanta Hawks: Successfully scraped!
[2023-05-02T01:52:53.837+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-02T01:52:53.846+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11261. PIDs of all processes in the group: [11261]
[2023-05-02T01:52:53.861+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11261
[2023-05-02T01:52:53.870+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-02T01:52:53.887+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-05-02T01:52:53.890+0000] {helpers.py:86} ERROR - Task received SIGTERM signal
[2023-05-02T01:52:53.891+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T01:52:54.909+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf621d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:54.914+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf621d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:54.923+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T01:52:55.950+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:55.952+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:55.954+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T01:52:56.964+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf626d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:56.969+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf626d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:56.970+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T01:52:57.982+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:57.984+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:57.986+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T01:52:58.996+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf624d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:59.006+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf624d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:52:59.008+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T01:53:00.027+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:00.034+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:00.036+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T01:53:01.049+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:01.052+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:01.053+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T01:53:02.062+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:02.064+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:02.065+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T01:53:03.078+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:03.079+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:03.080+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T01:53:04.087+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:04.089+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:04.090+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T01:53:05.105+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:05.109+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:05.111+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T01:53:06.120+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:06.123+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:06.125+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T01:53:07.181+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:07.277+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:07.279+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T01:53:08.302+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf629d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:08.306+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf629d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:08.310+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T01:53:09.323+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:09.334+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:09.338+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T01:53:10.347+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:10.348+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:10.350+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T01:53:11.360+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:11.362+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:11.364+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T01:53:12.370+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:12.374+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:12.376+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T01:53:13.391+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf626d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:13.393+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf626d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:13.396+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T01:53:14.407+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:14.411+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T01:53:14.412+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:25:37.111+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:37.113+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:37.118+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:25:38.129+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:38.131+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:38.134+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:25:39.143+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:39.146+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:39.147+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:25:40.295+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:40.349+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62ad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:40.361+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:25:41.379+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:41.381+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:41.383+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:25:42.414+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:42.419+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:42.423+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:25:43.446+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf626d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:43.450+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf626d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:43.456+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T02:25:44.476+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf622d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:44.478+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf622d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:44.488+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T02:25:45.532+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf621d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:45.546+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf621d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:45.549+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T02:25:46.576+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf629d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:46.586+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf629d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:46.600+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T02:25:47.629+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:47.630+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:47.633+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:25:48.644+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:48.650+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:48.652+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:25:49.659+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:49.660+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:49.664+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:25:50.674+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:50.676+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:50.677+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:25:51.810+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:51.811+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:51.812+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:25:52.838+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:52.853+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:52.858+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:25:53.867+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:53.869+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:53.871+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:25:54.917+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf629d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:54.926+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf629d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:54.928+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T02:25:55.949+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:55.953+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:55.956+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T02:25:56.984+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:56.990+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:56.994+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T02:25:58.030+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:58.032+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:58.035+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T02:25:59.064+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:59.067+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62c90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:25:59.072+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T02:26:00.093+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:00.099+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:00.104+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T02:26:01.159+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:01.162+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf62210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:01.164+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T02:26:02.188+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:02.195+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:02.197+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T02:26:03.253+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:03.256+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:03.257+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T02:26:04.284+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:04.290+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:04.292+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T02:26:05.323+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:05.332+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f2d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:05.336+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-05-02T02:26:06.350+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:06.351+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T02:26:06.353+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-05-02T03:16:33.975+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:33.976+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:33.978+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-05-02T03:16:34.991+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fb10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:34.998+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fb10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:35.009+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-02T03:16:36.017+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fe50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.019+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fe50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:36.020+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-02T03:16:37.028+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fe90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.030+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fe90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:37.033+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-02T03:16:38.046+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.050+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:38.051+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-02T03:16:39.062+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fe10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:39.064+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fe10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:39.065+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-05-02T03:16:40.073+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5ff90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:40.078+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5ff90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:40.081+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-05-02T03:16:41.092+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:41.095+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5fb90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:41.106+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-05-02T03:16:42.118+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:42.120+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9bf5f510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-02T03:16:42.122+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-05-02T03:16:42.161+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=11261, name='airflow task ru', status='sleeping', started='00:31:51') did not respond to SIGTERM. Trying SIGKILL
[2023-05-02T03:16:42.167+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 11261
[2023-05-02T03:16:42.221+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11261, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:31:51') (11261) terminated with exit code Negsignal.SIGKILL
[2023-05-02T03:16:42.223+0000] {standard_task_runner.py:170} ERROR - Job 2130 was killed before it finished (likely due to running out of memory)
