[2023-05-10T02:25:17.452+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 manual__2023-05-10T02:25:14.732891+00:00 [queued]>
[2023-05-10T02:25:17.479+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 manual__2023-05-10T02:25:14.732891+00:00 [queued]>
[2023-05-10T02:25:17.481+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-10T02:25:17.483+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-10T02:25:17.490+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-10T02:25:17.523+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_17-24> on 2023-05-10 02:25:14.732891+00:00
[2023-05-10T02:25:17.535+0000] {standard_task_runner.py:55} INFO - Started process 17564 to run task
[2023-05-10T02:25:17.568+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_17-24', 'manual__2023-05-10T02:25:14.732891+00:00', '--job-id', '4016', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_push_dag.py', '--cfg-path', '/tmp/tmp31cemzic']
[2023-05-10T02:25:17.600+0000] {standard_task_runner.py:83} INFO - Job 4016: Subtask scrape_teams_17-24
[2023-05-10T02:25:17.870+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_17-24 manual__2023-05-10T02:25:14.732891+00:00 [running]> on host f41dbfa3d325
[2023-05-10T02:25:17.962+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-10T02:25:18.062+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_17-24
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T02:25:14.732891+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-10T02:25:14.732891+00:00
[2023-05-10T02:25:19.636+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:19.656+0000] {helpers.py:99} ERROR - Retrying! 9 attempts before skipping!
[2023-05-10T02:25:21.336+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:21.338+0000] {helpers.py:99} ERROR - Retrying! 8 attempts before skipping!
[2023-05-10T02:25:23.379+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:23.380+0000] {helpers.py:99} ERROR - Retrying! 7 attempts before skipping!
[2023-05-10T02:25:25.175+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:25.177+0000] {helpers.py:99} ERROR - Retrying! 6 attempts before skipping!
[2023-05-10T02:25:26.894+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:26.896+0000] {helpers.py:99} ERROR - Retrying! 5 attempts before skipping!
[2023-05-10T02:25:28.763+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:28.765+0000] {helpers.py:99} ERROR - Retrying! 4 attempts before skipping!
[2023-05-10T02:25:30.465+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:30.466+0000] {helpers.py:99} ERROR - Retrying! 3 attempts before skipping!
[2023-05-10T02:25:32.145+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:32.146+0000] {helpers.py:99} ERROR - Retrying! 2 attempts before skipping!
[2023-05-10T02:25:33.873+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:33.875+0000] {helpers.py:99} ERROR - Retrying! 1 attempts before skipping!
[2023-05-10T02:25:35.861+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:35.867+0000] {helpers.py:99} ERROR - Retrying! 0 attempts before skipping!
[2023-05-10T02:25:37.613+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:37.614+0000] {helpers.py:99} ERROR - Retrying! -1 attempts before skipping!
[2023-05-10T02:25:39.417+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:39.418+0000] {helpers.py:99} ERROR - Retrying! 9 attempts before skipping!
[2023-05-10T02:25:41.380+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:41.382+0000] {helpers.py:99} ERROR - Retrying! 8 attempts before skipping!
[2023-05-10T02:25:43.074+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:43.075+0000] {helpers.py:99} ERROR - Retrying! 7 attempts before skipping!
[2023-05-10T02:25:44.882+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:44.884+0000] {helpers.py:99} ERROR - Retrying! 6 attempts before skipping!
[2023-05-10T02:25:46.998+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:47.000+0000] {helpers.py:99} ERROR - Retrying! 5 attempts before skipping!
[2023-05-10T02:25:48.694+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:48.701+0000] {helpers.py:99} ERROR - Retrying! 4 attempts before skipping!
[2023-05-10T02:25:50.546+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:50.548+0000] {helpers.py:99} ERROR - Retrying! 3 attempts before skipping!
[2023-05-10T02:25:53.856+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:53.858+0000] {helpers.py:99} ERROR - Retrying! 2 attempts before skipping!
[2023-05-10T02:25:59.217+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:25:59.219+0000] {helpers.py:99} ERROR - Retrying! 1 attempts before skipping!
[2023-05-10T02:26:05.985+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:05.988+0000] {helpers.py:99} ERROR - Retrying! 0 attempts before skipping!
[2023-05-10T02:26:13.200+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:13.201+0000] {helpers.py:99} ERROR - Retrying! -1 attempts before skipping!
[2023-05-10T02:26:20.982+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:20.984+0000] {helpers.py:99} ERROR - Retrying! 9 attempts before skipping!
[2023-05-10T02:26:28.610+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:28.611+0000] {helpers.py:99} ERROR - Retrying! 8 attempts before skipping!
[2023-05-10T02:26:36.355+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:36.357+0000] {helpers.py:99} ERROR - Retrying! 7 attempts before skipping!
[2023-05-10T02:26:44.637+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:44.642+0000] {helpers.py:99} ERROR - Retrying! 6 attempts before skipping!
[2023-05-10T02:26:52.966+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:26:52.968+0000] {helpers.py:99} ERROR - Retrying! 5 attempts before skipping!
[2023-05-10T02:26:58.543+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-10T02:26:58.551+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 17564. PIDs of all processes in the group: [17564]
[2023-05-10T02:26:58.552+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 17564
[2023-05-10T02:26:58.553+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-10T02:26:58.554+0000] {helpers.py:98} ERROR - Task received SIGTERM signal
[2023-05-10T02:26:58.555+0000] {helpers.py:99} ERROR - Retrying! 4 attempts before skipping!
[2023-05-10T02:27:00.666+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:00.670+0000] {helpers.py:99} ERROR - Retrying! 3 attempts before skipping!
[2023-05-10T02:27:08.583+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:08.584+0000] {helpers.py:99} ERROR - Retrying! 2 attempts before skipping!
[2023-05-10T02:27:16.350+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:16.354+0000] {helpers.py:99} ERROR - Retrying! 1 attempts before skipping!
[2023-05-10T02:27:23.964+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:23.966+0000] {helpers.py:99} ERROR - Retrying! 0 attempts before skipping!
[2023-05-10T02:27:30.726+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:30.729+0000] {helpers.py:99} ERROR - Retrying! -1 attempts before skipping!
[2023-05-10T02:27:37.444+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:37.446+0000] {helpers.py:99} ERROR - Retrying! 9 attempts before skipping!
[2023-05-10T02:27:44.728+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:44.731+0000] {helpers.py:99} ERROR - Retrying! 8 attempts before skipping!
[2023-05-10T02:27:51.482+0000] {helpers.py:98} ERROR - type object 'datetime.datetime' has no attribute 'datetime'
[2023-05-10T02:27:51.485+0000] {helpers.py:99} ERROR - Retrying! 7 attempts before skipping!
[2023-05-10T02:27:58.554+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=17564, name='airflow task ru', status='sleeping', started='02:25:17') did not respond to SIGTERM. Trying SIGKILL
[2023-05-10T02:27:58.566+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 17564
[2023-05-10T02:27:58.742+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=17564, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:25:17') (17564) terminated with exit code Negsignal.SIGKILL
[2023-05-10T02:27:58.749+0000] {standard_task_runner.py:170} ERROR - Job 4016 was killed before it finished (likely due to running out of memory)
