[2023-04-30T22:30:11.304+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-04-30T21:30:00+00:00 [queued]>
[2023-04-30T22:30:11.340+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-04-30T21:30:00+00:00 [queued]>
[2023-04-30T22:30:11.342+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T22:30:11.343+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-30T22:30:11.344+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T22:30:11.367+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): scrape_teams_1-8> on 2023-04-30 21:30:00+00:00
[2023-04-30T22:30:11.379+0000] {standard_task_runner.py:55} INFO - Started process 483 to run task
[2023-04-30T22:30:11.392+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'scrape_teams_1-8', 'scheduled__2023-04-30T21:30:00+00:00', '--job-id', '1960', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_save_csv_dag.py', '--cfg-path', '/tmp/tmp_ndlhghv']
[2023-04-30T22:30:11.396+0000] {standard_task_runner.py:83} INFO - Job 1960: Subtask scrape_teams_1-8
[2023-04-30T22:30:11.508+0000] {task_command.py:389} INFO - Running <TaskInstance: scrape_and_save_to_csv.scrape_teams_1-8 scheduled__2023-04-30T21:30:00+00:00 [running]> on host 5d4cd8acb346
[2023-04-30T22:30:11.607+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrape_and_save_to_csv
AIRFLOW_CTX_TASK_ID=scrape_teams_1-8
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T21:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T21:30:00+00:00
[2023-04-30T22:30:11.625+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:11.626+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:11.628+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T22:30:12.635+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:12.636+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:12.637+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T22:30:13.650+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:13.654+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:13.656+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T22:30:15.239+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:15.245+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:15.255+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T22:30:16.275+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:16.279+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:16.284+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T22:30:17.301+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:17.305+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:17.306+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T22:30:18.325+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:18.332+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:18.342+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T22:30:19.360+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:19.372+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:19.375+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T22:30:20.395+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:20.401+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:20.409+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T22:30:21.434+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:21.444+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:21.447+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T22:30:22.463+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:22.466+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=AtlantaHawks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:22.472+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T22:30:23.495+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:23.502+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:23.505+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T22:30:24.514+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:24.538+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:24.549+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T22:30:25.566+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:25.574+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:25.575+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T22:30:26.695+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:26.696+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:26.698+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T22:30:27.716+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:27.719+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:27.723+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T22:30:28.736+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:28.741+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:28.743+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T22:30:29.756+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:29.757+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:29.759+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T22:30:30.791+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:30.794+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:30.795+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T22:30:31.808+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:31.811+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:31.813+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T22:30:32.832+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:32.837+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:32.839+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T22:30:33.851+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:33.854+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=bostonceltics&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:33.856+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T22:30:34.869+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:34.871+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:34.873+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T22:30:35.885+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:35.887+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:35.893+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T22:30:36.905+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:36.907+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:36.912+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T22:30:37.958+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:38.029+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:38.031+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T22:30:39.057+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:39.060+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T22:30:39.067+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:19:46.860+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:46.869+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:46.875+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:19:47.897+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:47.901+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:47.904+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:19:48.918+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:48.922+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:48.924+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:19:49.952+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:49.954+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:49.956+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:19:50.971+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:50.975+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:50.976+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:19:52.005+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:52.009+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=gonets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:52.015+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:19:53.051+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:53.057+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:53.063+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:19:54.075+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:54.078+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:54.079+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:19:55.107+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:55.113+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:55.116+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:19:56.128+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:56.132+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:56.139+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:19:57.147+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:57.153+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:57.156+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:19:58.175+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:58.183+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:58.187+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:19:59.209+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:59.218+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:19:59.220+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:20:00.234+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:00.242+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:00.244+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:20:01.260+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:01.264+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:01.271+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:20:02.302+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:02.303+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053390>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:02.308+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:20:03.330+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:03.335+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=CharlotteHornets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:03.337+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:20:04.354+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:04.357+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:04.358+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:20:05.374+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:05.376+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:05.377+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:20:06.389+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:06.391+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:06.394+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:20:07.423+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:07.433+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:07.436+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:20:08.458+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:08.464+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:08.466+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:20:09.490+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:09.494+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:09.497+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:20:10.513+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:10.517+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:10.521+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:20:11.547+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:11.550+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:11.554+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:20:12.567+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:12.571+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:12.574+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:20:13.607+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:13.610+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:13.612+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:20:14.624+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:14.627+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=chicagobulls&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:14.629+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:20:15.645+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:15.649+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:20:15.652+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:51:43.321+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:43.324+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:43.325+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:51:44.338+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:44.340+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:44.342+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:51:45.358+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:45.361+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:45.364+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:51:46.379+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:46.385+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:46.387+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:51:47.397+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:47.399+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:47.400+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:51:48.428+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:48.430+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:48.432+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:51:49.444+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:49.446+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:49.448+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:51:50.457+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:50.459+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:50.461+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:51:51.470+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:51.471+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:51.473+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:51:52.484+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:52.489+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=clevelandcavs&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:52.490+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:51:53.513+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:53.519+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:53.522+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:51:54.537+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:54.544+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:54.548+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:51:55.589+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:55.594+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:55.595+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:51:56.604+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:56.606+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:56.608+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:51:57.639+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:57.643+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:57.646+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:51:58.660+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:58.664+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:58.667+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:51:59.677+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:59.680+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:51:59.682+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:52:00.702+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:00.705+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:00.707+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-04-30T23:52:01.715+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:01.716+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:01.718+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-04-30T23:52:02.729+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:02.730+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:02.732+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-04-30T23:52:03.743+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:03.744+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=Mavericks&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0053110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:03.745+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-04-30T23:52:04.752+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cf3e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:04.754+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa8cf3e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:04.756+0000] {helpers.py:87} ERROR - Retrying! 9 attempts before skipping!
[2023-04-30T23:52:05.766+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:05.768+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:05.768+0000] {helpers.py:87} ERROR - Retrying! 8 attempts before skipping!
[2023-04-30T23:52:06.809+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:06.813+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:06.815+0000] {helpers.py:87} ERROR - Retrying! 7 attempts before skipping!
[2023-04-30T23:52:07.834+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:07.837+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:07.842+0000] {helpers.py:87} ERROR - Retrying! 6 attempts before skipping!
[2023-04-30T23:52:08.870+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:08.873+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:08.880+0000] {helpers.py:87} ERROR - Retrying! 5 attempts before skipping!
[2023-04-30T23:52:09.911+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:09.915+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:09.919+0000] {helpers.py:87} ERROR - Retrying! 4 attempts before skipping!
[2023-04-30T23:52:10.934+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:10.936+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:10.937+0000] {helpers.py:87} ERROR - Retrying! 3 attempts before skipping!
[2023-04-30T23:52:11.948+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:11.950+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-04-30T23:52:11.951+0000] {helpers.py:87} ERROR - Retrying! 2 attempts before skipping!
[2023-05-01T00:40:02.834+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:02.837+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:02.839+0000] {helpers.py:87} ERROR - Retrying! 1 attempts before skipping!
[2023-05-01T00:40:03.850+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:03.856+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:03.858+0000] {helpers.py:87} ERROR - Retrying! 0 attempts before skipping!
[2023-05-01T00:40:04.867+0000] {logging_mixin.py:137} INFO - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:04.869+0000] {helpers.py:86} ERROR - HTTPSConnectionPool(host='api.pushshift.io', port=443): Max retries exceeded with url: /reddit/search/submission/?subreddit=denvernuggets&sort=created_utc&sort_type=desc&size=500 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0048f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-05-01T00:40:04.869+0000] {helpers.py:87} ERROR - Retrying! -1 attempts before skipping!
[2023-05-01T00:40:05.902+0000] {helpers.py:96} INFO - Saved in /opt/***/data/output_scrape_teams_1-8.csv
[2023-05-01T00:40:05.907+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-01T00:40:05.943+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=scrape_and_save_to_csv, task_id=scrape_teams_1-8, execution_date=20230430T213000, start_date=20230430T223011, end_date=20230501T004005
[2023-05-01T00:40:06.042+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-01T00:40:06.074+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
